// Protocol buffer definition for contract events processor.
//
// This schema defines the output format for all contract events extracted
// from Stellar ledgers, including contract invocations, token transfers,
// swaps, and custom contract events.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: contract_events.proto

package contract_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractEventType classifies the contract event.
type ContractEventType int32

const (
	// Standard contract event
	ContractEventType_CONTRACT ContractEventType = 0
	// System-level event
	ContractEventType_SYSTEM ContractEventType = 1
	// Diagnostic event
	ContractEventType_DIAGNOSTIC ContractEventType = 2
)

// Enum value maps for ContractEventType.
var (
	ContractEventType_name = map[int32]string{
		0: "CONTRACT",
		1: "SYSTEM",
		2: "DIAGNOSTIC",
	}
	ContractEventType_value = map[string]int32{
		"CONTRACT":   0,
		"SYSTEM":     1,
		"DIAGNOSTIC": 2,
	}
)

func (x ContractEventType) Enum() *ContractEventType {
	p := new(ContractEventType)
	*p = x
	return p
}

func (x ContractEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_events_proto_enumTypes[0].Descriptor()
}

func (ContractEventType) Type() protoreflect.EnumType {
	return &file_contract_events_proto_enumTypes[0]
}

func (x ContractEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractEventType.Descriptor instead.
func (ContractEventType) EnumDescriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{0}
}

// ContractEvent represents a single contract event emitted on-chain.
type ContractEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger close timestamp (Unix seconds)
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Ledger sequence number
	LedgerSequence uint32 `protobuf:"varint,2,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Transaction hash (hex-encoded)
	TransactionHash string `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	// Contract ID that emitted the event (strkey-encoded)
	ContractId string `protobuf:"bytes,4,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Event type classification
	Type ContractEventType `protobuf:"varint,5,opt,name=type,proto3,enum=contract_events.ContractEventType" json:"type,omitempty"`
	// Detected event type from topics (e.g., "transfer", "mint", "swap")
	EventType string `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Decoded topic values
	TopicDecoded []*ScVal `protobuf:"bytes,7,rep,name=topic_decoded,json=topicDecoded,proto3" json:"topic_decoded,omitempty"`
	// Decoded event data
	DataDecoded *ScVal `protobuf:"bytes,8,opt,name=data_decoded,json=dataDecoded,proto3" json:"data_decoded,omitempty"`
	// Whether this event was in a successful transaction
	InSuccessfulTx bool `protobuf:"varint,9,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	// Event index within the transaction
	EventIndex int32 `protobuf:"varint,10,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	// Operation index (-1 for transaction-level events)
	OperationIndex int32 `protobuf:"varint,11,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	// Diagnostic events associated with this contract event
	DiagnosticEvents []*DiagnosticEvent `protobuf:"bytes,12,rep,name=diagnostic_events,json=diagnosticEvents,proto3" json:"diagnostic_events,omitempty"`
	// Network passphrase
	NetworkPassphrase string `protobuf:"bytes,13,opt,name=network_passphrase,json=networkPassphrase,proto3" json:"network_passphrase,omitempty"`
	// Transaction index within the ledger
	TransactionIndex uint32 `protobuf:"varint,14,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContractEvent) Reset() {
	*x = ContractEvent{}
	mi := &file_contract_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractEvent) ProtoMessage() {}

func (x *ContractEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractEvent.ProtoReflect.Descriptor instead.
func (*ContractEvent) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{0}
}

func (x *ContractEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ContractEvent) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *ContractEvent) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *ContractEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractEvent) GetType() ContractEventType {
	if x != nil {
		return x.Type
	}
	return ContractEventType_CONTRACT
}

func (x *ContractEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ContractEvent) GetTopicDecoded() []*ScVal {
	if x != nil {
		return x.TopicDecoded
	}
	return nil
}

func (x *ContractEvent) GetDataDecoded() *ScVal {
	if x != nil {
		return x.DataDecoded
	}
	return nil
}

func (x *ContractEvent) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

func (x *ContractEvent) GetEventIndex() int32 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *ContractEvent) GetOperationIndex() int32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *ContractEvent) GetDiagnosticEvents() []*DiagnosticEvent {
	if x != nil {
		return x.DiagnosticEvents
	}
	return nil
}

func (x *ContractEvent) GetNetworkPassphrase() string {
	if x != nil {
		return x.NetworkPassphrase
	}
	return ""
}

func (x *ContractEvent) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

// ScVal represents a decoded Stellar Contract Value (ScVal).
// This maps XDR ScVal types to a JSON-friendly format.
type ScVal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ScVal_BoolValue
	//	*ScVal_VoidValue
	//	*ScVal_U32Value
	//	*ScVal_I32Value
	//	*ScVal_U64Value
	//	*ScVal_I64Value
	//	*ScVal_U128Value
	//	*ScVal_I128Value
	//	*ScVal_U256Value
	//	*ScVal_I256Value
	//	*ScVal_BytesValue
	//	*ScVal_StringValue
	//	*ScVal_SymbolValue
	//	*ScVal_VecValue
	//	*ScVal_MapValue
	//	*ScVal_AddressValue
	//	*ScVal_TimepointValue
	//	*ScVal_DurationValue
	//	*ScVal_LedgerKeyValue
	Value         isScVal_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScVal) Reset() {
	*x = ScVal{}
	mi := &file_contract_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScVal) ProtoMessage() {}

func (x *ScVal) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScVal.ProtoReflect.Descriptor instead.
func (*ScVal) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{1}
}

func (x *ScVal) GetValue() isScVal_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ScVal) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ScVal_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ScVal) GetVoidValue() *ScVoid {
	if x != nil {
		if x, ok := x.Value.(*ScVal_VoidValue); ok {
			return x.VoidValue
		}
	}
	return nil
}

func (x *ScVal) GetU32Value() uint32 {
	if x != nil {
		if x, ok := x.Value.(*ScVal_U32Value); ok {
			return x.U32Value
		}
	}
	return 0
}

func (x *ScVal) GetI32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*ScVal_I32Value); ok {
			return x.I32Value
		}
	}
	return 0
}

func (x *ScVal) GetU64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ScVal_U64Value); ok {
			return x.U64Value
		}
	}
	return 0
}

func (x *ScVal) GetI64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*ScVal_I64Value); ok {
			return x.I64Value
		}
	}
	return 0
}

func (x *ScVal) GetU128Value() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_U128Value); ok {
			return x.U128Value
		}
	}
	return ""
}

func (x *ScVal) GetI128Value() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_I128Value); ok {
			return x.I128Value
		}
	}
	return ""
}

func (x *ScVal) GetU256Value() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_U256Value); ok {
			return x.U256Value
		}
	}
	return ""
}

func (x *ScVal) GetI256Value() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_I256Value); ok {
			return x.I256Value
		}
	}
	return ""
}

func (x *ScVal) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*ScVal_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *ScVal) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ScVal) GetSymbolValue() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_SymbolValue); ok {
			return x.SymbolValue
		}
	}
	return ""
}

func (x *ScVal) GetVecValue() *ScVec {
	if x != nil {
		if x, ok := x.Value.(*ScVal_VecValue); ok {
			return x.VecValue
		}
	}
	return nil
}

func (x *ScVal) GetMapValue() *ScMap {
	if x != nil {
		if x, ok := x.Value.(*ScVal_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

func (x *ScVal) GetAddressValue() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_AddressValue); ok {
			return x.AddressValue
		}
	}
	return ""
}

func (x *ScVal) GetTimepointValue() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_TimepointValue); ok {
			return x.TimepointValue
		}
	}
	return ""
}

func (x *ScVal) GetDurationValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ScVal_DurationValue); ok {
			return x.DurationValue
		}
	}
	return 0
}

func (x *ScVal) GetLedgerKeyValue() string {
	if x != nil {
		if x, ok := x.Value.(*ScVal_LedgerKeyValue); ok {
			return x.LedgerKeyValue
		}
	}
	return ""
}

type isScVal_Value interface {
	isScVal_Value()
}

type ScVal_BoolValue struct {
	// Boolean value
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ScVal_VoidValue struct {
	// Void/null value
	VoidValue *ScVoid `protobuf:"bytes,2,opt,name=void_value,json=voidValue,proto3,oneof"`
}

type ScVal_U32Value struct {
	// Unsigned 32-bit integer
	U32Value uint32 `protobuf:"varint,3,opt,name=u32_value,json=u32Value,proto3,oneof"`
}

type ScVal_I32Value struct {
	// Signed 32-bit integer
	I32Value int32 `protobuf:"varint,4,opt,name=i32_value,json=i32Value,proto3,oneof"`
}

type ScVal_U64Value struct {
	// Unsigned 64-bit integer
	U64Value uint64 `protobuf:"varint,5,opt,name=u64_value,json=u64Value,proto3,oneof"`
}

type ScVal_I64Value struct {
	// Signed 64-bit integer
	I64Value int64 `protobuf:"varint,6,opt,name=i64_value,json=i64Value,proto3,oneof"`
}

type ScVal_U128Value struct {
	// 128-bit unsigned integer (hex string)
	U128Value string `protobuf:"bytes,7,opt,name=u128_value,json=u128Value,proto3,oneof"`
}

type ScVal_I128Value struct {
	// 128-bit signed integer (hex string)
	I128Value string `protobuf:"bytes,8,opt,name=i128_value,json=i128Value,proto3,oneof"`
}

type ScVal_U256Value struct {
	// 256-bit unsigned integer (hex string)
	U256Value string `protobuf:"bytes,9,opt,name=u256_value,json=u256Value,proto3,oneof"`
}

type ScVal_I256Value struct {
	// 256-bit signed integer (hex string)
	I256Value string `protobuf:"bytes,10,opt,name=i256_value,json=i256Value,proto3,oneof"`
}

type ScVal_BytesValue struct {
	// Byte array
	BytesValue []byte `protobuf:"bytes,11,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type ScVal_StringValue struct {
	// String value
	StringValue string `protobuf:"bytes,12,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ScVal_SymbolValue struct {
	// Symbol value
	SymbolValue string `protobuf:"bytes,13,opt,name=symbol_value,json=symbolValue,proto3,oneof"`
}

type ScVal_VecValue struct {
	// Vector (array) of values
	VecValue *ScVec `protobuf:"bytes,14,opt,name=vec_value,json=vecValue,proto3,oneof"`
}

type ScVal_MapValue struct {
	// Map of key-value pairs
	MapValue *ScMap `protobuf:"bytes,15,opt,name=map_value,json=mapValue,proto3,oneof"`
}

type ScVal_AddressValue struct {
	// Address (account or contract)
	AddressValue string `protobuf:"bytes,16,opt,name=address_value,json=addressValue,proto3,oneof"`
}

type ScVal_TimepointValue struct {
	// Timepoint (ISO8601 timestamp string)
	TimepointValue string `protobuf:"bytes,17,opt,name=timepoint_value,json=timepointValue,proto3,oneof"`
}

type ScVal_DurationValue struct {
	// Duration (seconds)
	DurationValue uint64 `protobuf:"varint,18,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type ScVal_LedgerKeyValue struct {
	// Ledger key types
	LedgerKeyValue string `protobuf:"bytes,19,opt,name=ledger_key_value,json=ledgerKeyValue,proto3,oneof"`
}

func (*ScVal_BoolValue) isScVal_Value() {}

func (*ScVal_VoidValue) isScVal_Value() {}

func (*ScVal_U32Value) isScVal_Value() {}

func (*ScVal_I32Value) isScVal_Value() {}

func (*ScVal_U64Value) isScVal_Value() {}

func (*ScVal_I64Value) isScVal_Value() {}

func (*ScVal_U128Value) isScVal_Value() {}

func (*ScVal_I128Value) isScVal_Value() {}

func (*ScVal_U256Value) isScVal_Value() {}

func (*ScVal_I256Value) isScVal_Value() {}

func (*ScVal_BytesValue) isScVal_Value() {}

func (*ScVal_StringValue) isScVal_Value() {}

func (*ScVal_SymbolValue) isScVal_Value() {}

func (*ScVal_VecValue) isScVal_Value() {}

func (*ScVal_MapValue) isScVal_Value() {}

func (*ScVal_AddressValue) isScVal_Value() {}

func (*ScVal_TimepointValue) isScVal_Value() {}

func (*ScVal_DurationValue) isScVal_Value() {}

func (*ScVal_LedgerKeyValue) isScVal_Value() {}

// ScVoid represents an empty/null value
type ScVoid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScVoid) Reset() {
	*x = ScVoid{}
	mi := &file_contract_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScVoid) ProtoMessage() {}

func (x *ScVoid) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScVoid.ProtoReflect.Descriptor instead.
func (*ScVoid) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{2}
}

// ScVec represents a vector (array) of ScVal values
type ScVec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ScVal               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScVec) Reset() {
	*x = ScVec{}
	mi := &file_contract_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScVec) ProtoMessage() {}

func (x *ScVec) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScVec.ProtoReflect.Descriptor instead.
func (*ScVec) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{3}
}

func (x *ScVec) GetValues() []*ScVal {
	if x != nil {
		return x.Values
	}
	return nil
}

// ScMap represents a map of key-value pairs
type ScMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ScMapEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScMap) Reset() {
	*x = ScMap{}
	mi := &file_contract_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScMap) ProtoMessage() {}

func (x *ScMap) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScMap.ProtoReflect.Descriptor instead.
func (*ScMap) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{4}
}

func (x *ScMap) GetEntries() []*ScMapEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ScMapEntry represents a single key-value pair in a map
type ScMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *ScVal                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           *ScVal                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScMapEntry) Reset() {
	*x = ScMapEntry{}
	mi := &file_contract_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScMapEntry) ProtoMessage() {}

func (x *ScMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScMapEntry.ProtoReflect.Descriptor instead.
func (*ScMapEntry) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{5}
}

func (x *ScMapEntry) GetKey() *ScVal {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScMapEntry) GetVal() *ScVal {
	if x != nil {
		return x.Val
	}
	return nil
}

// DiagnosticEvent captures diagnostic information from contract execution
type DiagnosticEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract ID that emitted the diagnostic event
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Event type
	Type ContractEventType `protobuf:"varint,2,opt,name=type,proto3,enum=contract_events.ContractEventType" json:"type,omitempty"`
	// Detected event type from topics
	EventType string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Decoded topic values
	TopicDecoded []*ScVal `protobuf:"bytes,4,rep,name=topic_decoded,json=topicDecoded,proto3" json:"topic_decoded,omitempty"`
	// Decoded event data
	DataDecoded *ScVal `protobuf:"bytes,5,opt,name=data_decoded,json=dataDecoded,proto3" json:"data_decoded,omitempty"`
	// Whether the contract call was successful
	InSuccessfulContractCall bool `protobuf:"varint,6,opt,name=in_successful_contract_call,json=inSuccessfulContractCall,proto3" json:"in_successful_contract_call,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiagnosticEvent) Reset() {
	*x = DiagnosticEvent{}
	mi := &file_contract_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticEvent) ProtoMessage() {}

func (x *DiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticEvent.ProtoReflect.Descriptor instead.
func (*DiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{6}
}

func (x *DiagnosticEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *DiagnosticEvent) GetType() ContractEventType {
	if x != nil {
		return x.Type
	}
	return ContractEventType_CONTRACT
}

func (x *DiagnosticEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DiagnosticEvent) GetTopicDecoded() []*ScVal {
	if x != nil {
		return x.TopicDecoded
	}
	return nil
}

func (x *DiagnosticEvent) GetDataDecoded() *ScVal {
	if x != nil {
		return x.DataDecoded
	}
	return nil
}

func (x *DiagnosticEvent) GetInSuccessfulContractCall() bool {
	if x != nil {
		return x.InSuccessfulContractCall
	}
	return false
}

// Metadata about the contract events processor
type ProcessorMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processor version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Schema version
	SchemaVersion string `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Network passphrase used for processing
	NetworkPassphrase string `protobuf:"bytes,3,opt,name=network_passphrase,json=networkPassphrase,proto3" json:"network_passphrase,omitempty"`
	// Total events processed
	TotalEvents uint64 `protobuf:"varint,4,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	// Processing start ledger
	StartLedger uint32 `protobuf:"varint,5,opt,name=start_ledger,json=startLedger,proto3" json:"start_ledger,omitempty"`
	// Processing end ledger (0 for unbounded)
	EndLedger     uint32 `protobuf:"varint,6,opt,name=end_ledger,json=endLedger,proto3" json:"end_ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorMetadata) Reset() {
	*x = ProcessorMetadata{}
	mi := &file_contract_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorMetadata) ProtoMessage() {}

func (x *ProcessorMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_contract_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorMetadata.ProtoReflect.Descriptor instead.
func (*ProcessorMetadata) Descriptor() ([]byte, []int) {
	return file_contract_events_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessorMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProcessorMetadata) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ProcessorMetadata) GetNetworkPassphrase() string {
	if x != nil {
		return x.NetworkPassphrase
	}
	return ""
}

func (x *ProcessorMetadata) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *ProcessorMetadata) GetStartLedger() uint32 {
	if x != nil {
		return x.StartLedger
	}
	return 0
}

func (x *ProcessorMetadata) GetEndLedger() uint32 {
	if x != nil {
		return x.EndLedger
	}
	return 0
}

var File_contract_events_proto protoreflect.FileDescriptor

const file_contract_events_proto_rawDesc = "" +
	"\n" +
	"\x15contract_events.proto\x12\x0fcontract_events\"\x90\x05\n" +
	"\rContractEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fledger_sequence\x18\x02 \x01(\rR\x0eledgerSequence\x12)\n" +
	"\x10transaction_hash\x18\x03 \x01(\tR\x0ftransactionHash\x12\x1f\n" +
	"\vcontract_id\x18\x04 \x01(\tR\n" +
	"contractId\x126\n" +
	"\x04type\x18\x05 \x01(\x0e2\".contract_events.ContractEventTypeR\x04type\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12;\n" +
	"\rtopic_decoded\x18\a \x03(\v2\x16.contract_events.ScValR\ftopicDecoded\x129\n" +
	"\fdata_decoded\x18\b \x01(\v2\x16.contract_events.ScValR\vdataDecoded\x12(\n" +
	"\x10in_successful_tx\x18\t \x01(\bR\x0einSuccessfulTx\x12\x1f\n" +
	"\vevent_index\x18\n" +
	" \x01(\x05R\n" +
	"eventIndex\x12'\n" +
	"\x0foperation_index\x18\v \x01(\x05R\x0eoperationIndex\x12M\n" +
	"\x11diagnostic_events\x18\f \x03(\v2 .contract_events.DiagnosticEventR\x10diagnosticEvents\x12-\n" +
	"\x12network_passphrase\x18\r \x01(\tR\x11networkPassphrase\x12+\n" +
	"\x11transaction_index\x18\x0e \x01(\rR\x10transactionIndex\"\xed\x05\n" +
	"\x05ScVal\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x128\n" +
	"\n" +
	"void_value\x18\x02 \x01(\v2\x17.contract_events.ScVoidH\x00R\tvoidValue\x12\x1d\n" +
	"\tu32_value\x18\x03 \x01(\rH\x00R\bu32Value\x12\x1d\n" +
	"\ti32_value\x18\x04 \x01(\x05H\x00R\bi32Value\x12\x1d\n" +
	"\tu64_value\x18\x05 \x01(\x04H\x00R\bu64Value\x12\x1d\n" +
	"\ti64_value\x18\x06 \x01(\x03H\x00R\bi64Value\x12\x1f\n" +
	"\n" +
	"u128_value\x18\a \x01(\tH\x00R\tu128Value\x12\x1f\n" +
	"\n" +
	"i128_value\x18\b \x01(\tH\x00R\ti128Value\x12\x1f\n" +
	"\n" +
	"u256_value\x18\t \x01(\tH\x00R\tu256Value\x12\x1f\n" +
	"\n" +
	"i256_value\x18\n" +
	" \x01(\tH\x00R\ti256Value\x12!\n" +
	"\vbytes_value\x18\v \x01(\fH\x00R\n" +
	"bytesValue\x12#\n" +
	"\fstring_value\x18\f \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fsymbol_value\x18\r \x01(\tH\x00R\vsymbolValue\x125\n" +
	"\tvec_value\x18\x0e \x01(\v2\x16.contract_events.ScVecH\x00R\bvecValue\x125\n" +
	"\tmap_value\x18\x0f \x01(\v2\x16.contract_events.ScMapH\x00R\bmapValue\x12%\n" +
	"\raddress_value\x18\x10 \x01(\tH\x00R\faddressValue\x12)\n" +
	"\x0ftimepoint_value\x18\x11 \x01(\tH\x00R\x0etimepointValue\x12'\n" +
	"\x0eduration_value\x18\x12 \x01(\x04H\x00R\rdurationValue\x12*\n" +
	"\x10ledger_key_value\x18\x13 \x01(\tH\x00R\x0eledgerKeyValueB\a\n" +
	"\x05value\"\b\n" +
	"\x06ScVoid\"7\n" +
	"\x05ScVec\x12.\n" +
	"\x06values\x18\x01 \x03(\v2\x16.contract_events.ScValR\x06values\">\n" +
	"\x05ScMap\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.contract_events.ScMapEntryR\aentries\"`\n" +
	"\n" +
	"ScMapEntry\x12(\n" +
	"\x03key\x18\x01 \x01(\v2\x16.contract_events.ScValR\x03key\x12(\n" +
	"\x03val\x18\x02 \x01(\v2\x16.contract_events.ScValR\x03val\"\xc0\x02\n" +
	"\x0fDiagnosticEvent\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x126\n" +
	"\x04type\x18\x02 \x01(\x0e2\".contract_events.ContractEventTypeR\x04type\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12;\n" +
	"\rtopic_decoded\x18\x04 \x03(\v2\x16.contract_events.ScValR\ftopicDecoded\x129\n" +
	"\fdata_decoded\x18\x05 \x01(\v2\x16.contract_events.ScValR\vdataDecoded\x12=\n" +
	"\x1bin_successful_contract_call\x18\x06 \x01(\bR\x18inSuccessfulContractCall\"\xe8\x01\n" +
	"\x11ProcessorMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\x12-\n" +
	"\x12network_passphrase\x18\x03 \x01(\tR\x11networkPassphrase\x12!\n" +
	"\ftotal_events\x18\x04 \x01(\x04R\vtotalEvents\x12!\n" +
	"\fstart_ledger\x18\x05 \x01(\rR\vstartLedger\x12\x1d\n" +
	"\n" +
	"end_ledger\x18\x06 \x01(\rR\tendLedger*=\n" +
	"\x11ContractEventType\x12\f\n" +
	"\bCONTRACT\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\x0e\n" +
	"\n" +
	"DIAGNOSTIC\x10\x02B@Z>github.com/withObsrvr/nebu-processor-registry/processors/contract-eventsb\x06proto3"

var (
	file_contract_events_proto_rawDescOnce sync.Once
	file_contract_events_proto_rawDescData []byte
)

func file_contract_events_proto_rawDescGZIP() []byte {
	file_contract_events_proto_rawDescOnce.Do(func() {
		file_contract_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_events_proto_rawDesc), len(file_contract_events_proto_rawDesc)))
	})
	return file_contract_events_proto_rawDescData
}

var file_contract_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_contract_events_proto_goTypes = []any{
	(ContractEventType)(0),    // 0: contract_events.ContractEventType
	(*ContractEvent)(nil),     // 1: contract_events.ContractEvent
	(*ScVal)(nil),             // 2: contract_events.ScVal
	(*ScVoid)(nil),            // 3: contract_events.ScVoid
	(*ScVec)(nil),             // 4: contract_events.ScVec
	(*ScMap)(nil),             // 5: contract_events.ScMap
	(*ScMapEntry)(nil),        // 6: contract_events.ScMapEntry
	(*DiagnosticEvent)(nil),   // 7: contract_events.DiagnosticEvent
	(*ProcessorMetadata)(nil), // 8: contract_events.ProcessorMetadata
}
var file_contract_events_proto_depIdxs = []int32{
	0,  // 0: contract_events.ContractEvent.type:type_name -> contract_events.ContractEventType
	2,  // 1: contract_events.ContractEvent.topic_decoded:type_name -> contract_events.ScVal
	2,  // 2: contract_events.ContractEvent.data_decoded:type_name -> contract_events.ScVal
	7,  // 3: contract_events.ContractEvent.diagnostic_events:type_name -> contract_events.DiagnosticEvent
	3,  // 4: contract_events.ScVal.void_value:type_name -> contract_events.ScVoid
	4,  // 5: contract_events.ScVal.vec_value:type_name -> contract_events.ScVec
	5,  // 6: contract_events.ScVal.map_value:type_name -> contract_events.ScMap
	2,  // 7: contract_events.ScVec.values:type_name -> contract_events.ScVal
	6,  // 8: contract_events.ScMap.entries:type_name -> contract_events.ScMapEntry
	2,  // 9: contract_events.ScMapEntry.key:type_name -> contract_events.ScVal
	2,  // 10: contract_events.ScMapEntry.val:type_name -> contract_events.ScVal
	0,  // 11: contract_events.DiagnosticEvent.type:type_name -> contract_events.ContractEventType
	2,  // 12: contract_events.DiagnosticEvent.topic_decoded:type_name -> contract_events.ScVal
	2,  // 13: contract_events.DiagnosticEvent.data_decoded:type_name -> contract_events.ScVal
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_contract_events_proto_init() }
func file_contract_events_proto_init() {
	if File_contract_events_proto != nil {
		return
	}
	file_contract_events_proto_msgTypes[1].OneofWrappers = []any{
		(*ScVal_BoolValue)(nil),
		(*ScVal_VoidValue)(nil),
		(*ScVal_U32Value)(nil),
		(*ScVal_I32Value)(nil),
		(*ScVal_U64Value)(nil),
		(*ScVal_I64Value)(nil),
		(*ScVal_U128Value)(nil),
		(*ScVal_I128Value)(nil),
		(*ScVal_U256Value)(nil),
		(*ScVal_I256Value)(nil),
		(*ScVal_BytesValue)(nil),
		(*ScVal_StringValue)(nil),
		(*ScVal_SymbolValue)(nil),
		(*ScVal_VecValue)(nil),
		(*ScVal_MapValue)(nil),
		(*ScVal_AddressValue)(nil),
		(*ScVal_TimepointValue)(nil),
		(*ScVal_DurationValue)(nil),
		(*ScVal_LedgerKeyValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_events_proto_rawDesc), len(file_contract_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_events_proto_goTypes,
		DependencyIndexes: file_contract_events_proto_depIdxs,
		EnumInfos:         file_contract_events_proto_enumTypes,
		MessageInfos:      file_contract_events_proto_msgTypes,
	}.Build()
	File_contract_events_proto = out.File
	file_contract_events_proto_goTypes = nil
	file_contract_events_proto_depIdxs = nil
}
