// Protocol buffer definition for TTL tracker processor.
//
// This schema defines the output format for TTL (time-to-live) changes
// extracted from Stellar ledgers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ttl_tracker.proto

package ttl_tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TtlEvent represents a TTL change for a contract data entry.
type TtlEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash of the ledger key this TTL applies to
	KeyHash string `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	// The ledger sequence at which this entry expires
	ExpirationLedger uint32 `protobuf:"varint,2,opt,name=expiration_ledger,json=expirationLedger,proto3" json:"expiration_ledger,omitempty"`
	// Operation type: "create", "update", or "delete"
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// Event metadata
	Meta          *EventMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtlEvent) Reset() {
	*x = TtlEvent{}
	mi := &file_ttl_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtlEvent) ProtoMessage() {}

func (x *TtlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ttl_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtlEvent.ProtoReflect.Descriptor instead.
func (*TtlEvent) Descriptor() ([]byte, []int) {
	return file_ttl_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TtlEvent) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *TtlEvent) GetExpirationLedger() uint32 {
	if x != nil {
		return x.ExpirationLedger
	}
	return 0
}

func (x *TtlEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TtlEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EventMeta contains chronological context for the event
type EventMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger sequence number
	LedgerSequence uint32 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Ledger close timestamp (Unix seconds)
	ClosedAtUnix int64 `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	// Transaction hash (hex-encoded)
	TxHash string `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Transaction index within the ledger
	TransactionIndex uint32 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_ttl_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ttl_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_ttl_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

var File_ttl_tracker_proto protoreflect.FileDescriptor

const file_ttl_tracker_proto_rawDesc = "" +
	"\n" +
	"\x11ttl_tracker.proto\x12\vttl_tracker\"\x9c\x01\n" +
	"\bTtlEvent\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\x12+\n" +
	"\x11expiration_ledger\x18\x02 \x01(\rR\x10expirationLedger\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12*\n" +
	"\x04meta\x18\n" +
	" \x01(\v2\x16.ttl_tracker.EventMetaR\x04meta\"\xa0\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndexBFZDgithub.com/withObsrvr/nebu-processor-registry/processors/ttl-trackerb\x06proto3"

var (
	file_ttl_tracker_proto_rawDescOnce sync.Once
	file_ttl_tracker_proto_rawDescData []byte
)

func file_ttl_tracker_proto_rawDescGZIP() []byte {
	file_ttl_tracker_proto_rawDescOnce.Do(func() {
		file_ttl_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ttl_tracker_proto_rawDesc), len(file_ttl_tracker_proto_rawDesc)))
	})
	return file_ttl_tracker_proto_rawDescData
}

var file_ttl_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ttl_tracker_proto_goTypes = []any{
	(*TtlEvent)(nil),  // 0: ttl_tracker.TtlEvent
	(*EventMeta)(nil), // 1: ttl_tracker.EventMeta
}
var file_ttl_tracker_proto_depIdxs = []int32{
	1, // 0: ttl_tracker.TtlEvent.meta:type_name -> ttl_tracker.EventMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ttl_tracker_proto_init() }
func file_ttl_tracker_proto_init() {
	if File_ttl_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ttl_tracker_proto_rawDesc), len(file_ttl_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ttl_tracker_proto_goTypes,
		DependencyIndexes: file_ttl_tracker_proto_depIdxs,
		MessageInfos:      file_ttl_tracker_proto_msgTypes,
	}.Build()
	File_ttl_tracker_proto = out.File
	file_ttl_tracker_proto_goTypes = nil
	file_ttl_tracker_proto_depIdxs = nil
}
