// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: validator_analytics.proto

package validator_analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidatorLedgerAnalytics contains deterministic facts extracted from one
// Stellar LedgerCloseMeta. Cross-ledger statistics such as close share,
// consecutive-leader streaks, or runs tests are deliberately left to
// downstream SQL and visualization tools.
type ValidatorLedgerAnalytics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence     uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix       int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	LedgerHash         string                 `protobuf:"bytes,3,opt,name=ledger_hash,json=ledgerHash,proto3" json:"ledger_hash,omitempty"`
	PreviousLedgerHash string                 `protobuf:"bytes,4,opt,name=previous_ledger_hash,json=previousLedgerHash,proto3" json:"previous_ledger_hash,omitempty"`
	ProtocolVersion    uint32                 `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	NetworkPassphrase  string                 `protobuf:"bytes,6,opt,name=network_passphrase,json=networkPassphrase,proto3" json:"network_passphrase,omitempty"`
	// Canonical G-address derived from the signed ledger-close value.
	ValidatorAddress string `protobuf:"bytes,7,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// Base64-encoded ledger-close signature.
	LedgerCloseSignature string `protobuf:"bytes,8,opt,name=ledger_close_signature,json=ledgerCloseSignature,proto3" json:"ledger_close_signature,omitempty"`
	// False for ledgers whose SCP value does not carry validator attribution.
	ValidatorAttributionAvailable bool   `protobuf:"varint,9,opt,name=validator_attribution_available,json=validatorAttributionAvailable,proto3" json:"validator_attribution_available,omitempty"`
	TransactionCount              uint32 `protobuf:"varint,10,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	SuccessfulTransactionCount    uint32 `protobuf:"varint,11,opt,name=successful_transaction_count,json=successfulTransactionCount,proto3" json:"successful_transaction_count,omitempty"`
	FailedTransactionCount        uint32 `protobuf:"varint,12,opt,name=failed_transaction_count,json=failedTransactionCount,proto3" json:"failed_transaction_count,omitempty"`
	// All operations included in the transaction set, including failed txs.
	OperationCount uint32 `protobuf:"varint,13,opt,name=operation_count,json=operationCount,proto3" json:"operation_count,omitempty"`
	// Operations belonging to successful transactions.
	SuccessfulOperationCount      uint32                   `protobuf:"varint,14,opt,name=successful_operation_count,json=successfulOperationCount,proto3" json:"successful_operation_count,omitempty"`
	OperationCategories           *OperationCategoryCounts `protobuf:"bytes,15,opt,name=operation_categories,json=operationCategories,proto3" json:"operation_categories,omitempty"`
	SuccessfulOperationCategories *OperationCategoryCounts `protobuf:"bytes,16,opt,name=successful_operation_categories,json=successfulOperationCategories,proto3" json:"successful_operation_categories,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ValidatorLedgerAnalytics) Reset() {
	*x = ValidatorLedgerAnalytics{}
	mi := &file_validator_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorLedgerAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorLedgerAnalytics) ProtoMessage() {}

func (x *ValidatorLedgerAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_validator_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorLedgerAnalytics.ProtoReflect.Descriptor instead.
func (*ValidatorLedgerAnalytics) Descriptor() ([]byte, []int) {
	return file_validator_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorLedgerAnalytics) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetLedgerHash() string {
	if x != nil {
		return x.LedgerHash
	}
	return ""
}

func (x *ValidatorLedgerAnalytics) GetPreviousLedgerHash() string {
	if x != nil {
		return x.PreviousLedgerHash
	}
	return ""
}

func (x *ValidatorLedgerAnalytics) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetNetworkPassphrase() string {
	if x != nil {
		return x.NetworkPassphrase
	}
	return ""
}

func (x *ValidatorLedgerAnalytics) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *ValidatorLedgerAnalytics) GetLedgerCloseSignature() string {
	if x != nil {
		return x.LedgerCloseSignature
	}
	return ""
}

func (x *ValidatorLedgerAnalytics) GetValidatorAttributionAvailable() bool {
	if x != nil {
		return x.ValidatorAttributionAvailable
	}
	return false
}

func (x *ValidatorLedgerAnalytics) GetTransactionCount() uint32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetSuccessfulTransactionCount() uint32 {
	if x != nil {
		return x.SuccessfulTransactionCount
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetFailedTransactionCount() uint32 {
	if x != nil {
		return x.FailedTransactionCount
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetOperationCount() uint32 {
	if x != nil {
		return x.OperationCount
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetSuccessfulOperationCount() uint32 {
	if x != nil {
		return x.SuccessfulOperationCount
	}
	return 0
}

func (x *ValidatorLedgerAnalytics) GetOperationCategories() *OperationCategoryCounts {
	if x != nil {
		return x.OperationCategories
	}
	return nil
}

func (x *ValidatorLedgerAnalytics) GetSuccessfulOperationCategories() *OperationCategoryCounts {
	if x != nil {
		return x.SuccessfulOperationCategories
	}
	return nil
}

// OperationCategoryCounts is an intentionally small, stable classification
// used by the validator-analytics experiment. Unknown and future operation
// types are counted as other until explicitly classified in a new schema.
type OperationCategoryCounts struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AccountCreation   uint32                 `protobuf:"varint,1,opt,name=account_creation,json=accountCreation,proto3" json:"account_creation,omitempty"`
	Payments          uint32                 `protobuf:"varint,2,opt,name=payments,proto3" json:"payments,omitempty"`
	OffersAndAmms     uint32                 `protobuf:"varint,3,opt,name=offers_and_amms,json=offersAndAmms,proto3" json:"offers_and_amms,omitempty"`
	Trustlines        uint32                 `protobuf:"varint,4,opt,name=trustlines,proto3" json:"trustlines,omitempty"`
	ClaimableBalances uint32                 `protobuf:"varint,5,opt,name=claimable_balances,json=claimableBalances,proto3" json:"claimable_balances,omitempty"`
	Sponsorship       uint32                 `protobuf:"varint,6,opt,name=sponsorship,proto3" json:"sponsorship,omitempty"`
	Soroban           uint32                 `protobuf:"varint,7,opt,name=soroban,proto3" json:"soroban,omitempty"`
	Other             uint32                 `protobuf:"varint,8,opt,name=other,proto3" json:"other,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OperationCategoryCounts) Reset() {
	*x = OperationCategoryCounts{}
	mi := &file_validator_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationCategoryCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCategoryCounts) ProtoMessage() {}

func (x *OperationCategoryCounts) ProtoReflect() protoreflect.Message {
	mi := &file_validator_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCategoryCounts.ProtoReflect.Descriptor instead.
func (*OperationCategoryCounts) Descriptor() ([]byte, []int) {
	return file_validator_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *OperationCategoryCounts) GetAccountCreation() uint32 {
	if x != nil {
		return x.AccountCreation
	}
	return 0
}

func (x *OperationCategoryCounts) GetPayments() uint32 {
	if x != nil {
		return x.Payments
	}
	return 0
}

func (x *OperationCategoryCounts) GetOffersAndAmms() uint32 {
	if x != nil {
		return x.OffersAndAmms
	}
	return 0
}

func (x *OperationCategoryCounts) GetTrustlines() uint32 {
	if x != nil {
		return x.Trustlines
	}
	return 0
}

func (x *OperationCategoryCounts) GetClaimableBalances() uint32 {
	if x != nil {
		return x.ClaimableBalances
	}
	return 0
}

func (x *OperationCategoryCounts) GetSponsorship() uint32 {
	if x != nil {
		return x.Sponsorship
	}
	return 0
}

func (x *OperationCategoryCounts) GetSoroban() uint32 {
	if x != nil {
		return x.Soroban
	}
	return 0
}

func (x *OperationCategoryCounts) GetOther() uint32 {
	if x != nil {
		return x.Other
	}
	return 0
}

var File_validator_analytics_proto protoreflect.FileDescriptor

const file_validator_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19validator_analytics.proto\x12\x13validator_analytics\"\xa8\a\n" +
	"\x18ValidatorLedgerAnalytics\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x1f\n" +
	"\vledger_hash\x18\x03 \x01(\tR\n" +
	"ledgerHash\x120\n" +
	"\x14previous_ledger_hash\x18\x04 \x01(\tR\x12previousLedgerHash\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\rR\x0fprotocolVersion\x12-\n" +
	"\x12network_passphrase\x18\x06 \x01(\tR\x11networkPassphrase\x12+\n" +
	"\x11validator_address\x18\a \x01(\tR\x10validatorAddress\x124\n" +
	"\x16ledger_close_signature\x18\b \x01(\tR\x14ledgerCloseSignature\x12F\n" +
	"\x1fvalidator_attribution_available\x18\t \x01(\bR\x1dvalidatorAttributionAvailable\x12+\n" +
	"\x11transaction_count\x18\n" +
	" \x01(\rR\x10transactionCount\x12@\n" +
	"\x1csuccessful_transaction_count\x18\v \x01(\rR\x1asuccessfulTransactionCount\x128\n" +
	"\x18failed_transaction_count\x18\f \x01(\rR\x16failedTransactionCount\x12'\n" +
	"\x0foperation_count\x18\r \x01(\rR\x0eoperationCount\x12<\n" +
	"\x1asuccessful_operation_count\x18\x0e \x01(\rR\x18successfulOperationCount\x12_\n" +
	"\x14operation_categories\x18\x0f \x01(\v2,.validator_analytics.OperationCategoryCountsR\x13operationCategories\x12t\n" +
	"\x1fsuccessful_operation_categories\x18\x10 \x01(\v2,.validator_analytics.OperationCategoryCountsR\x1dsuccessfulOperationCategories\"\xa9\x02\n" +
	"\x17OperationCategoryCounts\x12)\n" +
	"\x10account_creation\x18\x01 \x01(\rR\x0faccountCreation\x12\x1a\n" +
	"\bpayments\x18\x02 \x01(\rR\bpayments\x12&\n" +
	"\x0foffers_and_amms\x18\x03 \x01(\rR\roffersAndAmms\x12\x1e\n" +
	"\n" +
	"trustlines\x18\x04 \x01(\rR\n" +
	"trustlines\x12-\n" +
	"\x12claimable_balances\x18\x05 \x01(\rR\x11claimableBalances\x12 \n" +
	"\vsponsorship\x18\x06 \x01(\rR\vsponsorship\x12\x18\n" +
	"\asoroban\x18\a \x01(\rR\asoroban\x12\x14\n" +
	"\x05other\x18\b \x01(\rR\x05otherBNZLgithub.com/withObsrvr/nebu-processor-registry/processors/validator-analyticsb\x06proto3"

var (
	file_validator_analytics_proto_rawDescOnce sync.Once
	file_validator_analytics_proto_rawDescData []byte
)

func file_validator_analytics_proto_rawDescGZIP() []byte {
	file_validator_analytics_proto_rawDescOnce.Do(func() {
		file_validator_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validator_analytics_proto_rawDesc), len(file_validator_analytics_proto_rawDesc)))
	})
	return file_validator_analytics_proto_rawDescData
}

var file_validator_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_validator_analytics_proto_goTypes = []any{
	(*ValidatorLedgerAnalytics)(nil), // 0: validator_analytics.ValidatorLedgerAnalytics
	(*OperationCategoryCounts)(nil),  // 1: validator_analytics.OperationCategoryCounts
}
var file_validator_analytics_proto_depIdxs = []int32{
	1, // 0: validator_analytics.ValidatorLedgerAnalytics.operation_categories:type_name -> validator_analytics.OperationCategoryCounts
	1, // 1: validator_analytics.ValidatorLedgerAnalytics.successful_operation_categories:type_name -> validator_analytics.OperationCategoryCounts
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_validator_analytics_proto_init() }
func file_validator_analytics_proto_init() {
	if File_validator_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validator_analytics_proto_rawDesc), len(file_validator_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validator_analytics_proto_goTypes,
		DependencyIndexes: file_validator_analytics_proto_depIdxs,
		MessageInfos:      file_validator_analytics_proto_msgTypes,
	}.Build()
	File_validator_analytics_proto = out.File
	file_validator_analytics_proto_goTypes = nil
	file_validator_analytics_proto_depIdxs = nil
}
