// Protocol buffer definition for account effects processor.
//
// This schema defines the output format for account-level effects
// extracted from Stellar ledgers (non-payment operations).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: account_effects.proto

package account_effects

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountEffect represents an account-level mutation event.
type AccountEffect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect type (e.g., "trustline_created", "signer_updated", "offer_created")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Account affected
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// Effect-specific details as JSON string
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// Event metadata
	Meta          *EventMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountEffect) Reset() {
	*x = AccountEffect{}
	mi := &file_account_effects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEffect) ProtoMessage() {}

func (x *AccountEffect) ProtoReflect() protoreflect.Message {
	mi := &file_account_effects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEffect.ProtoReflect.Descriptor instead.
func (*AccountEffect) Descriptor() ([]byte, []int) {
	return file_account_effects_proto_rawDescGZIP(), []int{0}
}

func (x *AccountEffect) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccountEffect) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountEffect) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AccountEffect) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EventMeta contains chronological context for the event.
type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   uint32                 `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,6,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_account_effects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_account_effects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_account_effects_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

var File_account_effects_proto protoreflect.FileDescriptor

const file_account_effects_proto_rawDesc = "" +
	"\n" +
	"\x15account_effects.proto\x12\x0faccount_effects\"\x87\x01\n" +
	"\rAccountEffect\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12.\n" +
	"\x04meta\x18\n" +
	" \x01(\v2\x1a.account_effects.EventMetaR\x04meta\"\xf3\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\rR\x0eoperationIndex\x12(\n" +
	"\x10in_successful_tx\x18\x06 \x01(\bR\x0einSuccessfulTxBJZHgithub.com/withObsrvr/nebu-processor-registry/processors/account-effectsb\x06proto3"

var (
	file_account_effects_proto_rawDescOnce sync.Once
	file_account_effects_proto_rawDescData []byte
)

func file_account_effects_proto_rawDescGZIP() []byte {
	file_account_effects_proto_rawDescOnce.Do(func() {
		file_account_effects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_effects_proto_rawDesc), len(file_account_effects_proto_rawDesc)))
	})
	return file_account_effects_proto_rawDescData
}

var file_account_effects_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_account_effects_proto_goTypes = []any{
	(*AccountEffect)(nil), // 0: account_effects.AccountEffect
	(*EventMeta)(nil),     // 1: account_effects.EventMeta
}
var file_account_effects_proto_depIdxs = []int32{
	1, // 0: account_effects.AccountEffect.meta:type_name -> account_effects.EventMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_effects_proto_init() }
func file_account_effects_proto_init() {
	if File_account_effects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_effects_proto_rawDesc), len(file_account_effects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_effects_proto_goTypes,
		DependencyIndexes: file_account_effects_proto_depIdxs,
		MessageInfos:      file_account_effects_proto_msgTypes,
	}.Build()
	File_account_effects_proto = out.File
	file_account_effects_proto_goTypes = nil
	file_account_effects_proto_depIdxs = nil
}
