// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: nft_events.proto

package nft_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   int32                  `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	EventIndex       int32                  `protobuf:"varint,6,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,7,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_nft_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_nft_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_nft_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() int32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetEventIndex() int32 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

type NftEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Meta                 *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ContractId           string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	TokenId              string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Action               string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Standard             string                 `protobuf:"bytes,5,opt,name=standard,proto3" json:"standard,omitempty"`
	Implementation       string                 `protobuf:"bytes,6,opt,name=implementation,proto3" json:"implementation,omitempty"`
	ClassificationSource string                 `protobuf:"bytes,7,opt,name=classification_source,json=classificationSource,proto3" json:"classification_source,omitempty"`
	Confidence           float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	From                 string                 `protobuf:"bytes,9,opt,name=from,proto3" json:"from,omitempty"`
	To                   string                 `protobuf:"bytes,10,opt,name=to,proto3" json:"to,omitempty"`
	Owner                string                 `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	Approved             string                 `protobuf:"bytes,12,opt,name=approved,proto3" json:"approved,omitempty"`
	Operator             string                 `protobuf:"bytes,13,opt,name=operator,proto3" json:"operator,omitempty"`
	FunctionName         string                 `protobuf:"bytes,14,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	TokenMetadataUri     string                 `protobuf:"bytes,15,opt,name=token_metadata_uri,json=tokenMetadataUri,proto3" json:"token_metadata_uri,omitempty"`
	MetadataStorage      string                 `protobuf:"bytes,16,opt,name=metadata_storage,json=metadataStorage,proto3" json:"metadata_storage,omitempty"`
	MethodsDetected      []string               `protobuf:"bytes,17,rep,name=methods_detected,json=methodsDetected,proto3" json:"methods_detected,omitempty"`
	EventTypesDetected   []string               `protobuf:"bytes,18,rep,name=event_types_detected,json=eventTypesDetected,proto3" json:"event_types_detected,omitempty"`
	RawTopics            []string               `protobuf:"bytes,19,rep,name=raw_topics,json=rawTopics,proto3" json:"raw_topics,omitempty"`
	RawData              string                 `protobuf:"bytes,20,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	SourceKind           string                 `protobuf:"bytes,21,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	CollectionName       string                 `protobuf:"bytes,22,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Symbol               string                 `protobuf:"bytes,23,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StateKey             string                 `protobuf:"bytes,24,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	StateValue           string                 `protobuf:"bytes,25,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	Durability           string                 `protobuf:"bytes,26,opt,name=durability,proto3" json:"durability,omitempty"`
	TokenExists          bool                   `protobuf:"varint,27,opt,name=token_exists,json=tokenExists,proto3" json:"token_exists,omitempty"`
	Burned               bool                   `protobuf:"varint,28,opt,name=burned,proto3" json:"burned,omitempty"`
	HeuristicRuleIds     []string               `protobuf:"bytes,29,rep,name=heuristic_rule_ids,json=heuristicRuleIds,proto3" json:"heuristic_rule_ids,omitempty"`
	HeuristicReasons     []string               `protobuf:"bytes,30,rep,name=heuristic_reasons,json=heuristicReasons,proto3" json:"heuristic_reasons,omitempty"`
	HeuristicTags        []string               `protobuf:"bytes,31,rep,name=heuristic_tags,json=heuristicTags,proto3" json:"heuristic_tags,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NftEvent) Reset() {
	*x = NftEvent{}
	mi := &file_nft_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NftEvent) ProtoMessage() {}

func (x *NftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nft_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NftEvent.ProtoReflect.Descriptor instead.
func (*NftEvent) Descriptor() ([]byte, []int) {
	return file_nft_events_proto_rawDescGZIP(), []int{1}
}

func (x *NftEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *NftEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NftEvent) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *NftEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *NftEvent) GetStandard() string {
	if x != nil {
		return x.Standard
	}
	return ""
}

func (x *NftEvent) GetImplementation() string {
	if x != nil {
		return x.Implementation
	}
	return ""
}

func (x *NftEvent) GetClassificationSource() string {
	if x != nil {
		return x.ClassificationSource
	}
	return ""
}

func (x *NftEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *NftEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *NftEvent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *NftEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *NftEvent) GetApproved() string {
	if x != nil {
		return x.Approved
	}
	return ""
}

func (x *NftEvent) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *NftEvent) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *NftEvent) GetTokenMetadataUri() string {
	if x != nil {
		return x.TokenMetadataUri
	}
	return ""
}

func (x *NftEvent) GetMetadataStorage() string {
	if x != nil {
		return x.MetadataStorage
	}
	return ""
}

func (x *NftEvent) GetMethodsDetected() []string {
	if x != nil {
		return x.MethodsDetected
	}
	return nil
}

func (x *NftEvent) GetEventTypesDetected() []string {
	if x != nil {
		return x.EventTypesDetected
	}
	return nil
}

func (x *NftEvent) GetRawTopics() []string {
	if x != nil {
		return x.RawTopics
	}
	return nil
}

func (x *NftEvent) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *NftEvent) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *NftEvent) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *NftEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *NftEvent) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *NftEvent) GetStateValue() string {
	if x != nil {
		return x.StateValue
	}
	return ""
}

func (x *NftEvent) GetDurability() string {
	if x != nil {
		return x.Durability
	}
	return ""
}

func (x *NftEvent) GetTokenExists() bool {
	if x != nil {
		return x.TokenExists
	}
	return false
}

func (x *NftEvent) GetBurned() bool {
	if x != nil {
		return x.Burned
	}
	return false
}

func (x *NftEvent) GetHeuristicRuleIds() []string {
	if x != nil {
		return x.HeuristicRuleIds
	}
	return nil
}

func (x *NftEvent) GetHeuristicReasons() []string {
	if x != nil {
		return x.HeuristicReasons
	}
	return nil
}

func (x *NftEvent) GetHeuristicTags() []string {
	if x != nil {
		return x.HeuristicTags
	}
	return nil
}

var File_nft_events_proto protoreflect.FileDescriptor

const file_nft_events_proto_rawDesc = "" +
	"\n" +
	"\x10nft_events.proto\x12\n" +
	"nft_events\"\x94\x02\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\x05R\x0eoperationIndex\x12\x1f\n" +
	"\vevent_index\x18\x06 \x01(\x05R\n" +
	"eventIndex\x12(\n" +
	"\x10in_successful_tx\x18\a \x01(\bR\x0einSuccessfulTx\"\xa6\b\n" +
	"\bNftEvent\x12)\n" +
	"\x04meta\x18\x01 \x01(\v2\x15.nft_events.EventMetaR\x04meta\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bstandard\x18\x05 \x01(\tR\bstandard\x12&\n" +
	"\x0eimplementation\x18\x06 \x01(\tR\x0eimplementation\x123\n" +
	"\x15classification_source\x18\a \x01(\tR\x14classificationSource\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x12\n" +
	"\x04from\x18\t \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\n" +
	" \x01(\tR\x02to\x12\x14\n" +
	"\x05owner\x18\v \x01(\tR\x05owner\x12\x1a\n" +
	"\bapproved\x18\f \x01(\tR\bapproved\x12\x1a\n" +
	"\boperator\x18\r \x01(\tR\boperator\x12#\n" +
	"\rfunction_name\x18\x0e \x01(\tR\ffunctionName\x12,\n" +
	"\x12token_metadata_uri\x18\x0f \x01(\tR\x10tokenMetadataUri\x12)\n" +
	"\x10metadata_storage\x18\x10 \x01(\tR\x0fmetadataStorage\x12)\n" +
	"\x10methods_detected\x18\x11 \x03(\tR\x0fmethodsDetected\x120\n" +
	"\x14event_types_detected\x18\x12 \x03(\tR\x12eventTypesDetected\x12\x1d\n" +
	"\n" +
	"raw_topics\x18\x13 \x03(\tR\trawTopics\x12\x19\n" +
	"\braw_data\x18\x14 \x01(\tR\arawData\x12\x1f\n" +
	"\vsource_kind\x18\x15 \x01(\tR\n" +
	"sourceKind\x12'\n" +
	"\x0fcollection_name\x18\x16 \x01(\tR\x0ecollectionName\x12\x16\n" +
	"\x06symbol\x18\x17 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tstate_key\x18\x18 \x01(\tR\bstateKey\x12\x1f\n" +
	"\vstate_value\x18\x19 \x01(\tR\n" +
	"stateValue\x12\x1e\n" +
	"\n" +
	"durability\x18\x1a \x01(\tR\n" +
	"durability\x12!\n" +
	"\ftoken_exists\x18\x1b \x01(\bR\vtokenExists\x12\x16\n" +
	"\x06burned\x18\x1c \x01(\bR\x06burned\x12,\n" +
	"\x12heuristic_rule_ids\x18\x1d \x03(\tR\x10heuristicRuleIds\x12+\n" +
	"\x11heuristic_reasons\x18\x1e \x03(\tR\x10heuristicReasons\x12%\n" +
	"\x0eheuristic_tags\x18\x1f \x03(\tR\rheuristicTagsBPZNgithub.com/withObsrvr/nebu-processor-registry/processors/nft-events;nft_eventsb\x06proto3"

var (
	file_nft_events_proto_rawDescOnce sync.Once
	file_nft_events_proto_rawDescData []byte
)

func file_nft_events_proto_rawDescGZIP() []byte {
	file_nft_events_proto_rawDescOnce.Do(func() {
		file_nft_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nft_events_proto_rawDesc), len(file_nft_events_proto_rawDesc)))
	})
	return file_nft_events_proto_rawDescData
}

var file_nft_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nft_events_proto_goTypes = []any{
	(*EventMeta)(nil), // 0: nft_events.EventMeta
	(*NftEvent)(nil),  // 1: nft_events.NftEvent
}
var file_nft_events_proto_depIdxs = []int32{
	0, // 0: nft_events.NftEvent.meta:type_name -> nft_events.EventMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nft_events_proto_init() }
func file_nft_events_proto_init() {
	if File_nft_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nft_events_proto_rawDesc), len(file_nft_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nft_events_proto_goTypes,
		DependencyIndexes: file_nft_events_proto_depIdxs,
		MessageInfos:      file_nft_events_proto_msgTypes,
	}.Build()
	File_nft_events_proto = out.File
	file_nft_events_proto_goTypes = nil
	file_nft_events_proto_depIdxs = nil
}
