// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: soroban_tx_resources.proto

package soroban_tx_resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SorobanTxResources carries the per-transaction facts that no other nebu
// origin emits: the declared Soroban resource footprint including ledger ENTRY
// counts, the decoded transaction and contract result codes, the fee actually
// charged against the fee bid, and the serialized envelope size.
//
// These are the inputs a ledger-capacity view needs. Utilisation is
// deliberately not computed here: the caps live in ConfigSettingEntry and
// change by protocol upgrade, so dividing by them is a downstream join, not a
// fact about this transaction.
//
// One event is emitted per transaction in the ledger's transaction set,
// including failed transactions, in apply order.
type SorobanTxResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the transaction applied. Mirrors TransactionResult.Successful().
	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	// Canonical Horizon-style transaction result code, e.g. "tx_SUCCESS",
	// "tx_BAD_SEQ", "tx_FAILED". Decoded from TransactionResultCode.
	ResultCode string `protobuf:"bytes,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	// Per-operation result codes in operation order, e.g.
	// "op_INVOKE_HOST_FUNCTION_TRAPPED". Empty when the transaction failed
	// before operations were attempted.
	OperationResultCodes []string `protobuf:"bytes,3,rep,name=operation_result_codes,json=operationResultCodes,proto3" json:"operation_result_codes,omitempty"`
	// Source account of the transaction (G-address, or the fee account for a
	// fee bump).
	SourceAccount  string `protobuf:"bytes,4,opt,name=source_account,json=sourceAccount,proto3" json:"source_account,omitempty"`
	OperationCount uint32 `protobuf:"varint,5,opt,name=operation_count,json=operationCount,proto3" json:"operation_count,omitempty"`
	IsSoroban      bool   `protobuf:"varint,6,opt,name=is_soroban,json=isSoroban,proto3" json:"is_soroban,omitempty"`
	IsFeeBump      bool   `protobuf:"varint,7,opt,name=is_fee_bump,json=isFeeBump,proto3" json:"is_fee_bump,omitempty"`
	// Set when a diagnostic event carries an ScError. Distinguishes a contract
	// declining to proceed from a host or client fault.
	ContractErrorPresent bool `protobuf:"varint,10,opt,name=contract_error_present,json=contractErrorPresent,proto3" json:"contract_error_present,omitempty"`
	// ScErrorType as a lowercase string: "contract", "wasm_vm", "budget",
	// "storage", "context", "object", "crypto", "events", "auth", "value".
	ContractErrorType string `protobuf:"bytes,11,opt,name=contract_error_type,json=contractErrorType,proto3" json:"contract_error_type,omitempty"`
	// The contract's own error number — the "#4" in "#4 HealthFactorTooLow".
	// Only meaningful when contract_error_type is "contract".
	ContractErrorCode uint32 `protobuf:"varint,12,opt,name=contract_error_code,json=contractErrorCode,proto3" json:"contract_error_code,omitempty"`
	// Fee actually charged. In a contested ledger this is the clearing price and
	// is identical across every included transaction.
	FeeChargedStroops int64 `protobuf:"varint,20,opt,name=fee_charged_stroops,json=feeChargedStroops,proto3" json:"fee_charged_stroops,omitempty"`
	// The bid: the maximum fee the submitter was willing to pay. A transaction
	// charged far below its bid is evidence the fee market did not clear at the
	// bid.
	MaxFeeStroops int64 `protobuf:"varint,21,opt,name=max_fee_stroops,json=maxFeeStroops,proto3" json:"max_fee_stroops,omitempty"`
	// Soroban resource fee declared in SorobanTransactionData. Zero for classic.
	ResourceFeeStroops int64 `protobuf:"varint,22,opt,name=resource_fee_stroops,json=resourceFeeStroops,proto3" json:"resource_fee_stroops,omitempty"`
	// Length in bytes of the marshaled TransactionEnvelope. Summed across a
	// ledger this is the transaction-size utilisation numerator.
	EnvelopeSizeBytes uint32 `protobuf:"varint,30,opt,name=envelope_size_bytes,json=envelopeSizeBytes,proto3" json:"envelope_size_bytes,omitempty"`
	Instructions      uint32 `protobuf:"varint,40,opt,name=instructions,proto3" json:"instructions,omitempty"`
	DiskReadBytes     uint32 `protobuf:"varint,41,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	WriteBytes        uint32 `protobuf:"varint,42,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	// len(SorobanResources.Footprint.ReadOnly).
	ReadOnlyEntries uint32 `protobuf:"varint,43,opt,name=read_only_entries,json=readOnlyEntries,proto3" json:"read_only_entries,omitempty"`
	// len(SorobanResources.Footprint.ReadWrite). Summed across a ledger this is
	// the ledger write-entry utilisation numerator, to be divided by
	// ConfigSettingContractLedgerCostV0.ledgerMaxWriteLedgerEntries.
	ReadWriteEntries uint32     `protobuf:"varint,44,opt,name=read_write_entries,json=readWriteEntries,proto3" json:"read_write_entries,omitempty"`
	Meta             *EventMeta `protobuf:"bytes,50,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SorobanTxResources) Reset() {
	*x = SorobanTxResources{}
	mi := &file_soroban_tx_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SorobanTxResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SorobanTxResources) ProtoMessage() {}

func (x *SorobanTxResources) ProtoReflect() protoreflect.Message {
	mi := &file_soroban_tx_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SorobanTxResources.ProtoReflect.Descriptor instead.
func (*SorobanTxResources) Descriptor() ([]byte, []int) {
	return file_soroban_tx_resources_proto_rawDescGZIP(), []int{0}
}

func (x *SorobanTxResources) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *SorobanTxResources) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *SorobanTxResources) GetOperationResultCodes() []string {
	if x != nil {
		return x.OperationResultCodes
	}
	return nil
}

func (x *SorobanTxResources) GetSourceAccount() string {
	if x != nil {
		return x.SourceAccount
	}
	return ""
}

func (x *SorobanTxResources) GetOperationCount() uint32 {
	if x != nil {
		return x.OperationCount
	}
	return 0
}

func (x *SorobanTxResources) GetIsSoroban() bool {
	if x != nil {
		return x.IsSoroban
	}
	return false
}

func (x *SorobanTxResources) GetIsFeeBump() bool {
	if x != nil {
		return x.IsFeeBump
	}
	return false
}

func (x *SorobanTxResources) GetContractErrorPresent() bool {
	if x != nil {
		return x.ContractErrorPresent
	}
	return false
}

func (x *SorobanTxResources) GetContractErrorType() string {
	if x != nil {
		return x.ContractErrorType
	}
	return ""
}

func (x *SorobanTxResources) GetContractErrorCode() uint32 {
	if x != nil {
		return x.ContractErrorCode
	}
	return 0
}

func (x *SorobanTxResources) GetFeeChargedStroops() int64 {
	if x != nil {
		return x.FeeChargedStroops
	}
	return 0
}

func (x *SorobanTxResources) GetMaxFeeStroops() int64 {
	if x != nil {
		return x.MaxFeeStroops
	}
	return 0
}

func (x *SorobanTxResources) GetResourceFeeStroops() int64 {
	if x != nil {
		return x.ResourceFeeStroops
	}
	return 0
}

func (x *SorobanTxResources) GetEnvelopeSizeBytes() uint32 {
	if x != nil {
		return x.EnvelopeSizeBytes
	}
	return 0
}

func (x *SorobanTxResources) GetInstructions() uint32 {
	if x != nil {
		return x.Instructions
	}
	return 0
}

func (x *SorobanTxResources) GetDiskReadBytes() uint32 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *SorobanTxResources) GetWriteBytes() uint32 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *SorobanTxResources) GetReadOnlyEntries() uint32 {
	if x != nil {
		return x.ReadOnlyEntries
	}
	return 0
}

func (x *SorobanTxResources) GetReadWriteEntries() uint32 {
	if x != nil {
		return x.ReadWriteEntries
	}
	return 0
}

func (x *SorobanTxResources) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EventMeta follows the registry's standard metadata shape.
type EventMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix   int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash         string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Position of the transaction within the ledger's applied transaction set.
	// Stellar shuffles apply order deterministically from the previous ledger
	// hash, so this is apply order, not fee order.
	TransactionIndex uint32 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_soroban_tx_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_soroban_tx_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_soroban_tx_resources_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

var File_soroban_tx_resources_proto protoreflect.FileDescriptor

const file_soroban_tx_resources_proto_rawDesc = "" +
	"\n" +
	"\x1asoroban_tx_resources.proto\x12\x14soroban_tx_resources\"\xe6\x06\n" +
	"\x12SorobanTxResources\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\x12\x1f\n" +
	"\vresult_code\x18\x02 \x01(\tR\n" +
	"resultCode\x124\n" +
	"\x16operation_result_codes\x18\x03 \x03(\tR\x14operationResultCodes\x12%\n" +
	"\x0esource_account\x18\x04 \x01(\tR\rsourceAccount\x12'\n" +
	"\x0foperation_count\x18\x05 \x01(\rR\x0eoperationCount\x12\x1d\n" +
	"\n" +
	"is_soroban\x18\x06 \x01(\bR\tisSoroban\x12\x1e\n" +
	"\vis_fee_bump\x18\a \x01(\bR\tisFeeBump\x124\n" +
	"\x16contract_error_present\x18\n" +
	" \x01(\bR\x14contractErrorPresent\x12.\n" +
	"\x13contract_error_type\x18\v \x01(\tR\x11contractErrorType\x12.\n" +
	"\x13contract_error_code\x18\f \x01(\rR\x11contractErrorCode\x12.\n" +
	"\x13fee_charged_stroops\x18\x14 \x01(\x03R\x11feeChargedStroops\x12&\n" +
	"\x0fmax_fee_stroops\x18\x15 \x01(\x03R\rmaxFeeStroops\x120\n" +
	"\x14resource_fee_stroops\x18\x16 \x01(\x03R\x12resourceFeeStroops\x12.\n" +
	"\x13envelope_size_bytes\x18\x1e \x01(\rR\x11envelopeSizeBytes\x12\"\n" +
	"\finstructions\x18( \x01(\rR\finstructions\x12&\n" +
	"\x0fdisk_read_bytes\x18) \x01(\rR\rdiskReadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18* \x01(\rR\n" +
	"writeBytes\x12*\n" +
	"\x11read_only_entries\x18+ \x01(\rR\x0freadOnlyEntries\x12,\n" +
	"\x12read_write_entries\x18, \x01(\rR\x10readWriteEntries\x123\n" +
	"\x04meta\x182 \x01(\v2\x1f.soroban_tx_resources.EventMetaR\x04meta\"\xa0\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndexBOZMgithub.com/withObsrvr/nebu-processor-registry/processors/soroban-tx-resourcesb\x06proto3"

var (
	file_soroban_tx_resources_proto_rawDescOnce sync.Once
	file_soroban_tx_resources_proto_rawDescData []byte
)

func file_soroban_tx_resources_proto_rawDescGZIP() []byte {
	file_soroban_tx_resources_proto_rawDescOnce.Do(func() {
		file_soroban_tx_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soroban_tx_resources_proto_rawDesc), len(file_soroban_tx_resources_proto_rawDesc)))
	})
	return file_soroban_tx_resources_proto_rawDescData
}

var file_soroban_tx_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_soroban_tx_resources_proto_goTypes = []any{
	(*SorobanTxResources)(nil), // 0: soroban_tx_resources.SorobanTxResources
	(*EventMeta)(nil),          // 1: soroban_tx_resources.EventMeta
}
var file_soroban_tx_resources_proto_depIdxs = []int32{
	1, // 0: soroban_tx_resources.SorobanTxResources.meta:type_name -> soroban_tx_resources.EventMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_soroban_tx_resources_proto_init() }
func file_soroban_tx_resources_proto_init() {
	if File_soroban_tx_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soroban_tx_resources_proto_rawDesc), len(file_soroban_tx_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_soroban_tx_resources_proto_goTypes,
		DependencyIndexes: file_soroban_tx_resources_proto_depIdxs,
		MessageInfos:      file_soroban_tx_resources_proto_msgTypes,
	}.Build()
	File_soroban_tx_resources_proto = out.File
	file_soroban_tx_resources_proto_goTypes = nil
	file_soroban_tx_resources_proto_depIdxs = nil
}
