// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: examples/processors/amount-filter/proto/amount_filter.proto

package amount_filter_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmountFilterService_Configure_FullMethodName       = "/nebu.amount_filter.AmountFilterService/Configure"
	AmountFilterService_GetConfig_FullMethodName       = "/nebu.amount_filter.AmountFilterService/GetConfig"
	AmountFilterService_Transform_FullMethodName       = "/nebu.amount_filter.AmountFilterService/Transform"
	AmountFilterService_TransformStream_FullMethodName = "/nebu.amount_filter.AmountFilterService/TransformStream"
)

// AmountFilterServiceClient is the client API for AmountFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AmountFilterService is a gRPC transform service for filtering events by amount
type AmountFilterServiceClient interface {
	// Configure sets the filter parameters
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// GetConfig returns the current filter configuration
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Transform applies the filter to a single event
	Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error)
	// TransformStream applies the filter to a stream of events
	TransformStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformRequest, TransformResponse], error)
}

type amountFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmountFilterServiceClient(cc grpc.ClientConnInterface) AmountFilterServiceClient {
	return &amountFilterServiceClient{cc}
}

func (c *amountFilterServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, AmountFilterService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amountFilterServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, AmountFilterService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amountFilterServiceClient) Transform(ctx context.Context, in *TransformRequest, opts ...grpc.CallOption) (*TransformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransformResponse)
	err := c.cc.Invoke(ctx, AmountFilterService_Transform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amountFilterServiceClient) TransformStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransformRequest, TransformResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AmountFilterService_ServiceDesc.Streams[0], AmountFilterService_TransformStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransformRequest, TransformResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AmountFilterService_TransformStreamClient = grpc.BidiStreamingClient[TransformRequest, TransformResponse]

// AmountFilterServiceServer is the server API for AmountFilterService service.
// All implementations must embed UnimplementedAmountFilterServiceServer
// for forward compatibility.
//
// AmountFilterService is a gRPC transform service for filtering events by amount
type AmountFilterServiceServer interface {
	// Configure sets the filter parameters
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// GetConfig returns the current filter configuration
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Transform applies the filter to a single event
	Transform(context.Context, *TransformRequest) (*TransformResponse, error)
	// TransformStream applies the filter to a stream of events
	TransformStream(grpc.BidiStreamingServer[TransformRequest, TransformResponse]) error
	mustEmbedUnimplementedAmountFilterServiceServer()
}

// UnimplementedAmountFilterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmountFilterServiceServer struct{}

func (UnimplementedAmountFilterServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedAmountFilterServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAmountFilterServiceServer) Transform(context.Context, *TransformRequest) (*TransformResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedAmountFilterServiceServer) TransformStream(grpc.BidiStreamingServer[TransformRequest, TransformResponse]) error {
	return status.Error(codes.Unimplemented, "method TransformStream not implemented")
}
func (UnimplementedAmountFilterServiceServer) mustEmbedUnimplementedAmountFilterServiceServer() {}
func (UnimplementedAmountFilterServiceServer) testEmbeddedByValue()                             {}

// UnsafeAmountFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmountFilterServiceServer will
// result in compilation errors.
type UnsafeAmountFilterServiceServer interface {
	mustEmbedUnimplementedAmountFilterServiceServer()
}

func RegisterAmountFilterServiceServer(s grpc.ServiceRegistrar, srv AmountFilterServiceServer) {
	// If the following call panics, it indicates UnimplementedAmountFilterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmountFilterService_ServiceDesc, srv)
}

func _AmountFilterService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmountFilterServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmountFilterService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmountFilterServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmountFilterService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmountFilterServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmountFilterService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmountFilterServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmountFilterService_Transform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmountFilterServiceServer).Transform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmountFilterService_Transform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmountFilterServiceServer).Transform(ctx, req.(*TransformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmountFilterService_TransformStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmountFilterServiceServer).TransformStream(&grpc.GenericServerStream[TransformRequest, TransformResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AmountFilterService_TransformStreamServer = grpc.BidiStreamingServer[TransformRequest, TransformResponse]

// AmountFilterService_ServiceDesc is the grpc.ServiceDesc for AmountFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmountFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebu.amount_filter.AmountFilterService",
	HandlerType: (*AmountFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _AmountFilterService_Configure_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AmountFilterService_GetConfig_Handler,
		},
		{
			MethodName: "Transform",
			Handler:    _AmountFilterService_Transform_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransformStream",
			Handler:       _AmountFilterService_TransformStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "examples/processors/amount-filter/proto/amount_filter.proto",
}
