// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: examples/processors/amount-filter/proto/amount_filter.proto

package amount_filter_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransformRequest contains a single event to transform
type TransformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded event
	EventJson     []byte `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{0}
}

func (x *TransformRequest) GetEventJson() []byte {
	if x != nil {
		return x.EventJson
	}
	return nil
}

// TransformResponse contains the transformed event or indicates it was filtered
type TransformResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded transformed event (empty if filtered out)
	EventJson []byte `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	// Whether the event was filtered out
	Filtered      bool `protobuf:"varint,2,opt,name=filtered,proto3" json:"filtered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{1}
}

func (x *TransformResponse) GetEventJson() []byte {
	if x != nil {
		return x.EventJson
	}
	return nil
}

func (x *TransformResponse) GetFiltered() bool {
	if x != nil {
		return x.Filtered
	}
	return false
}

// FilterConfig configures the amount filter parameters
type FilterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Minimum amount (inclusive, in stroops). 0 = no minimum
	MinAmount int64 `protobuf:"varint,1,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	// Maximum amount (inclusive, in stroops). 0 = no maximum
	MaxAmount int64 `protobuf:"varint,2,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	// Asset code to filter by (e.g., "USDC", "XLM"). Empty = any asset
	AssetCode     string `protobuf:"bytes,3,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterConfig) Reset() {
	*x = FilterConfig{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterConfig) ProtoMessage() {}

func (x *FilterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterConfig.ProtoReflect.Descriptor instead.
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{2}
}

func (x *FilterConfig) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *FilterConfig) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *FilterConfig) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

// ConfigureRequest sets the filter parameters
type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FilterConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureRequest) GetConfig() *FilterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigureResponse confirms configuration was applied
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetConfigRequest requests the current configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{5}
}

// GetConfigResponse returns the current configuration
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FilterConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetConfig() *FilterConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_examples_processors_amount_filter_proto_amount_filter_proto protoreflect.FileDescriptor

const file_examples_processors_amount_filter_proto_amount_filter_proto_rawDesc = "" +
	"\n" +
	";examples/processors/amount-filter/proto/amount_filter.proto\x12\x12nebu.amount_filter\"1\n" +
	"\x10TransformRequest\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\fR\teventJson\"N\n" +
	"\x11TransformResponse\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\fR\teventJson\x12\x1a\n" +
	"\bfiltered\x18\x02 \x01(\bR\bfiltered\"k\n" +
	"\fFilterConfig\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x01 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x02 \x01(\x03R\tmaxAmount\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x03 \x01(\tR\tassetCode\"L\n" +
	"\x10ConfigureRequest\x128\n" +
	"\x06config\x18\x01 \x01(\v2 .nebu.amount_filter.FilterConfigR\x06config\"G\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10GetConfigRequest\"M\n" +
	"\x11GetConfigResponse\x128\n" +
	"\x06config\x18\x01 \x01(\v2 .nebu.amount_filter.FilterConfigR\x06config2\x87\x03\n" +
	"\x13AmountFilterService\x12X\n" +
	"\tConfigure\x12$.nebu.amount_filter.ConfigureRequest\x1a%.nebu.amount_filter.ConfigureResponse\x12X\n" +
	"\tGetConfig\x12$.nebu.amount_filter.GetConfigRequest\x1a%.nebu.amount_filter.GetConfigResponse\x12X\n" +
	"\tTransform\x12$.nebu.amount_filter.TransformRequest\x1a%.nebu.amount_filter.TransformResponse\x12b\n" +
	"\x0fTransformStream\x12$.nebu.amount_filter.TransformRequest\x1a%.nebu.amount_filter.TransformResponse(\x010\x01BUZSgithub.com/withObsrvr/nebu-processor-registry/processors/amount-filter/proto;amount_filter_pbb\x06proto3"

var (
	file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescOnce sync.Once
	file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescData []byte
)

func file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescGZIP() []byte {
	file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescOnce.Do(func() {
		file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_processors_amount_filter_proto_amount_filter_proto_rawDesc), len(file_examples_processors_amount_filter_proto_amount_filter_proto_rawDesc)))
	})
	return file_examples_processors_amount_filter_proto_amount_filter_proto_rawDescData
}

var file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_examples_processors_amount_filter_proto_amount_filter_proto_goTypes = []any{
	(*TransformRequest)(nil),  // 0: nebu.amount_filter.TransformRequest
	(*TransformResponse)(nil), // 1: nebu.amount_filter.TransformResponse
	(*FilterConfig)(nil),      // 2: nebu.amount_filter.FilterConfig
	(*ConfigureRequest)(nil),  // 3: nebu.amount_filter.ConfigureRequest
	(*ConfigureResponse)(nil), // 4: nebu.amount_filter.ConfigureResponse
	(*GetConfigRequest)(nil),  // 5: nebu.amount_filter.GetConfigRequest
	(*GetConfigResponse)(nil), // 6: nebu.amount_filter.GetConfigResponse
}
var file_examples_processors_amount_filter_proto_amount_filter_proto_depIdxs = []int32{
	2, // 0: nebu.amount_filter.ConfigureRequest.config:type_name -> nebu.amount_filter.FilterConfig
	2, // 1: nebu.amount_filter.GetConfigResponse.config:type_name -> nebu.amount_filter.FilterConfig
	3, // 2: nebu.amount_filter.AmountFilterService.Configure:input_type -> nebu.amount_filter.ConfigureRequest
	5, // 3: nebu.amount_filter.AmountFilterService.GetConfig:input_type -> nebu.amount_filter.GetConfigRequest
	0, // 4: nebu.amount_filter.AmountFilterService.Transform:input_type -> nebu.amount_filter.TransformRequest
	0, // 5: nebu.amount_filter.AmountFilterService.TransformStream:input_type -> nebu.amount_filter.TransformRequest
	4, // 6: nebu.amount_filter.AmountFilterService.Configure:output_type -> nebu.amount_filter.ConfigureResponse
	6, // 7: nebu.amount_filter.AmountFilterService.GetConfig:output_type -> nebu.amount_filter.GetConfigResponse
	1, // 8: nebu.amount_filter.AmountFilterService.Transform:output_type -> nebu.amount_filter.TransformResponse
	1, // 9: nebu.amount_filter.AmountFilterService.TransformStream:output_type -> nebu.amount_filter.TransformResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_processors_amount_filter_proto_amount_filter_proto_init() }
func file_examples_processors_amount_filter_proto_amount_filter_proto_init() {
	if File_examples_processors_amount_filter_proto_amount_filter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_processors_amount_filter_proto_amount_filter_proto_rawDesc), len(file_examples_processors_amount_filter_proto_amount_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_processors_amount_filter_proto_amount_filter_proto_goTypes,
		DependencyIndexes: file_examples_processors_amount_filter_proto_amount_filter_proto_depIdxs,
		MessageInfos:      file_examples_processors_amount_filter_proto_amount_filter_proto_msgTypes,
	}.Build()
	File_examples_processors_amount_filter_proto_amount_filter_proto = out.File
	file_examples_processors_amount_filter_proto_amount_filter_proto_goTypes = nil
	file_examples_processors_amount_filter_proto_amount_filter_proto_depIdxs = nil
}
