// Protocol buffer definition for liquidity pool events processor.
//
// This schema defines the output format for liquidity pool operations
// extracted from Stellar ledgers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: liquidity_pool_events.proto

package liquidity_pool_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiquidityPoolEvent represents a liquidity pool operation.
type LiquidityPoolEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation type: "deposit", "withdraw", or "trade"
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Pool ID (hex-encoded)
	PoolId string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// Account performing the operation
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// Assets involved in the operation
	Assets []*PoolAsset `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets,omitempty"`
	// Shares minted (deposit) or burned (withdraw)
	Shares string `protobuf:"bytes,5,opt,name=shares,proto3" json:"shares,omitempty"`
	// Pool reserves before the operation
	ReservesBefore []*ReserveAmount `protobuf:"bytes,6,rep,name=reserves_before,json=reservesBefore,proto3" json:"reserves_before,omitempty"`
	// Pool reserves after the operation
	ReservesAfter []*ReserveAmount `protobuf:"bytes,7,rep,name=reserves_after,json=reservesAfter,proto3" json:"reserves_after,omitempty"`
	// Event metadata
	Meta          *EventMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiquidityPoolEvent) Reset() {
	*x = LiquidityPoolEvent{}
	mi := &file_liquidity_pool_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiquidityPoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidityPoolEvent) ProtoMessage() {}

func (x *LiquidityPoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_liquidity_pool_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiquidityPoolEvent.ProtoReflect.Descriptor instead.
func (*LiquidityPoolEvent) Descriptor() ([]byte, []int) {
	return file_liquidity_pool_events_proto_rawDescGZIP(), []int{0}
}

func (x *LiquidityPoolEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LiquidityPoolEvent) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *LiquidityPoolEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LiquidityPoolEvent) GetAssets() []*PoolAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *LiquidityPoolEvent) GetShares() string {
	if x != nil {
		return x.Shares
	}
	return ""
}

func (x *LiquidityPoolEvent) GetReservesBefore() []*ReserveAmount {
	if x != nil {
		return x.ReservesBefore
	}
	return nil
}

func (x *LiquidityPoolEvent) GetReservesAfter() []*ReserveAmount {
	if x != nil {
		return x.ReservesAfter
	}
	return nil
}

func (x *LiquidityPoolEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// PoolAsset represents an asset and amount in a pool operation.
type PoolAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetType     string                 `protobuf:"bytes,1,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAsset) Reset() {
	*x = PoolAsset{}
	mi := &file_liquidity_pool_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAsset) ProtoMessage() {}

func (x *PoolAsset) ProtoReflect() protoreflect.Message {
	mi := &file_liquidity_pool_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAsset.ProtoReflect.Descriptor instead.
func (*PoolAsset) Descriptor() ([]byte, []int) {
	return file_liquidity_pool_events_proto_rawDescGZIP(), []int{1}
}

func (x *PoolAsset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *PoolAsset) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *PoolAsset) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *PoolAsset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// ReserveAmount represents a pool reserve.
type ReserveAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetType     string                 `protobuf:"bytes,1,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveAmount) Reset() {
	*x = ReserveAmount{}
	mi := &file_liquidity_pool_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveAmount) ProtoMessage() {}

func (x *ReserveAmount) ProtoReflect() protoreflect.Message {
	mi := &file_liquidity_pool_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveAmount.ProtoReflect.Descriptor instead.
func (*ReserveAmount) Descriptor() ([]byte, []int) {
	return file_liquidity_pool_events_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveAmount) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *ReserveAmount) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *ReserveAmount) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *ReserveAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// EventMeta contains chronological context for the event.
type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   uint32                 `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,6,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_liquidity_pool_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_liquidity_pool_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_liquidity_pool_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

var File_liquidity_pool_events_proto protoreflect.FileDescriptor

const file_liquidity_pool_events_proto_rawDesc = "" +
	"\n" +
	"\x1bliquidity_pool_events.proto\x12\x15liquidity_pool_events\"\xff\x02\n" +
	"\x12LiquidityPoolEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x128\n" +
	"\x06assets\x18\x04 \x03(\v2 .liquidity_pool_events.PoolAssetR\x06assets\x12\x16\n" +
	"\x06shares\x18\x05 \x01(\tR\x06shares\x12M\n" +
	"\x0freserves_before\x18\x06 \x03(\v2$.liquidity_pool_events.ReserveAmountR\x0ereservesBefore\x12K\n" +
	"\x0ereserves_after\x18\a \x03(\v2$.liquidity_pool_events.ReserveAmountR\rreservesAfter\x124\n" +
	"\x04meta\x18\n" +
	" \x01(\v2 .liquidity_pool_events.EventMetaR\x04meta\"\x84\x01\n" +
	"\tPoolAsset\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x01 \x01(\tR\tassetType\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"\x88\x01\n" +
	"\rReserveAmount\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x01 \x01(\tR\tassetType\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"\xf3\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\rR\x0eoperationIndex\x12(\n" +
	"\x10in_successful_tx\x18\x06 \x01(\bR\x0einSuccessfulTxBPZNgithub.com/withObsrvr/nebu-processor-registry/processors/liquidity-pool-eventsb\x06proto3"

var (
	file_liquidity_pool_events_proto_rawDescOnce sync.Once
	file_liquidity_pool_events_proto_rawDescData []byte
)

func file_liquidity_pool_events_proto_rawDescGZIP() []byte {
	file_liquidity_pool_events_proto_rawDescOnce.Do(func() {
		file_liquidity_pool_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liquidity_pool_events_proto_rawDesc), len(file_liquidity_pool_events_proto_rawDesc)))
	})
	return file_liquidity_pool_events_proto_rawDescData
}

var file_liquidity_pool_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_liquidity_pool_events_proto_goTypes = []any{
	(*LiquidityPoolEvent)(nil), // 0: liquidity_pool_events.LiquidityPoolEvent
	(*PoolAsset)(nil),          // 1: liquidity_pool_events.PoolAsset
	(*ReserveAmount)(nil),      // 2: liquidity_pool_events.ReserveAmount
	(*EventMeta)(nil),          // 3: liquidity_pool_events.EventMeta
}
var file_liquidity_pool_events_proto_depIdxs = []int32{
	1, // 0: liquidity_pool_events.LiquidityPoolEvent.assets:type_name -> liquidity_pool_events.PoolAsset
	2, // 1: liquidity_pool_events.LiquidityPoolEvent.reserves_before:type_name -> liquidity_pool_events.ReserveAmount
	2, // 2: liquidity_pool_events.LiquidityPoolEvent.reserves_after:type_name -> liquidity_pool_events.ReserveAmount
	3, // 3: liquidity_pool_events.LiquidityPoolEvent.meta:type_name -> liquidity_pool_events.EventMeta
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_liquidity_pool_events_proto_init() }
func file_liquidity_pool_events_proto_init() {
	if File_liquidity_pool_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liquidity_pool_events_proto_rawDesc), len(file_liquidity_pool_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_liquidity_pool_events_proto_goTypes,
		DependencyIndexes: file_liquidity_pool_events_proto_depIdxs,
		MessageInfos:      file_liquidity_pool_events_proto_msgTypes,
	}.Build()
	File_liquidity_pool_events_proto = out.File
	file_liquidity_pool_events_proto_goTypes = nil
	file_liquidity_pool_events_proto_depIdxs = nil
}
