// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: contract_created.proto

package contract_created

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   int32                  `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,6,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_contract_created_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_contract_created_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_contract_created_proto_rawDescGZIP(), []int{0}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() int32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

type StateEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Durability    string                 `protobuf:"bytes,4,opt,name=durability,proto3" json:"durability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEntry) Reset() {
	*x = StateEntry{}
	mi := &file_contract_created_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEntry) ProtoMessage() {}

func (x *StateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_contract_created_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEntry.ProtoReflect.Descriptor instead.
func (*StateEntry) Descriptor() ([]byte, []int) {
	return file_contract_created_proto_rawDescGZIP(), []int{1}
}

func (x *StateEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StateEntry) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StateEntry) GetDurability() string {
	if x != nil {
		return x.Durability
	}
	return ""
}

type FamilyCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasons       []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	RuleIds       []string               `protobuf:"bytes,5,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyCandidate) Reset() {
	*x = FamilyCandidate{}
	mi := &file_contract_created_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyCandidate) ProtoMessage() {}

func (x *FamilyCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_contract_created_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyCandidate.ProtoReflect.Descriptor instead.
func (*FamilyCandidate) Descriptor() ([]byte, []int) {
	return file_contract_created_proto_rawDescGZIP(), []int{2}
}

func (x *FamilyCandidate) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *FamilyCandidate) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FamilyCandidate) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *FamilyCandidate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FamilyCandidate) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

type ContractCreatedEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Meta                    *EventMeta             `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ContractId              string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Deployer                string                 `protobuf:"bytes,3,opt,name=deployer,proto3" json:"deployer,omitempty"`
	PreimageAddress         string                 `protobuf:"bytes,4,opt,name=preimage_address,json=preimageAddress,proto3" json:"preimage_address,omitempty"`
	SaltHex                 string                 `protobuf:"bytes,5,opt,name=salt_hex,json=saltHex,proto3" json:"salt_hex,omitempty"`
	ExecutableType          string                 `protobuf:"bytes,6,opt,name=executable_type,json=executableType,proto3" json:"executable_type,omitempty"`
	WasmHash                string                 `protobuf:"bytes,7,opt,name=wasm_hash,json=wasmHash,proto3" json:"wasm_hash,omitempty"`
	CreateHostFunctionType  string                 `protobuf:"bytes,8,opt,name=create_host_function_type,json=createHostFunctionType,proto3" json:"create_host_function_type,omitempty"`
	ConstructorInvoked      bool                   `protobuf:"varint,9,opt,name=constructor_invoked,json=constructorInvoked,proto3" json:"constructor_invoked,omitempty"`
	ConstructorName         string                 `protobuf:"bytes,10,opt,name=constructor_name,json=constructorName,proto3" json:"constructor_name,omitempty"`
	ConstructorArgs         []string               `protobuf:"bytes,11,rep,name=constructor_args,json=constructorArgs,proto3" json:"constructor_args,omitempty"`
	ContractInstanceCreated bool                   `protobuf:"varint,12,opt,name=contract_instance_created,json=contractInstanceCreated,proto3" json:"contract_instance_created,omitempty"`
	InitializedState        []*StateEntry          `protobuf:"bytes,13,rep,name=initialized_state,json=initializedState,proto3" json:"initialized_state,omitempty"`
	TtlExtendedToLedger     uint32                 `protobuf:"varint,14,opt,name=ttl_extended_to_ledger,json=ttlExtendedToLedger,proto3" json:"ttl_extended_to_ledger,omitempty"`
	ClassificationHint      string                 `protobuf:"bytes,15,opt,name=classification_hint,json=classificationHint,proto3" json:"classification_hint,omitempty"`
	ClassificationReasons   []string               `protobuf:"bytes,16,rep,name=classification_reasons,json=classificationReasons,proto3" json:"classification_reasons,omitempty"`
	FamilyHint              string                 `protobuf:"bytes,17,opt,name=family_hint,json=familyHint,proto3" json:"family_hint,omitempty"`
	FamilyConfidence        float64                `protobuf:"fixed64,18,opt,name=family_confidence,json=familyConfidence,proto3" json:"family_confidence,omitempty"`
	FamilyReasons           []string               `protobuf:"bytes,19,rep,name=family_reasons,json=familyReasons,proto3" json:"family_reasons,omitempty"`
	FamilyTags              []string               `protobuf:"bytes,20,rep,name=family_tags,json=familyTags,proto3" json:"family_tags,omitempty"`
	FamilyCandidates        []*FamilyCandidate     `protobuf:"bytes,21,rep,name=family_candidates,json=familyCandidates,proto3" json:"family_candidates,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContractCreatedEvent) Reset() {
	*x = ContractCreatedEvent{}
	mi := &file_contract_created_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCreatedEvent) ProtoMessage() {}

func (x *ContractCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_created_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCreatedEvent.ProtoReflect.Descriptor instead.
func (*ContractCreatedEvent) Descriptor() ([]byte, []int) {
	return file_contract_created_proto_rawDescGZIP(), []int{3}
}

func (x *ContractCreatedEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContractCreatedEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractCreatedEvent) GetDeployer() string {
	if x != nil {
		return x.Deployer
	}
	return ""
}

func (x *ContractCreatedEvent) GetPreimageAddress() string {
	if x != nil {
		return x.PreimageAddress
	}
	return ""
}

func (x *ContractCreatedEvent) GetSaltHex() string {
	if x != nil {
		return x.SaltHex
	}
	return ""
}

func (x *ContractCreatedEvent) GetExecutableType() string {
	if x != nil {
		return x.ExecutableType
	}
	return ""
}

func (x *ContractCreatedEvent) GetWasmHash() string {
	if x != nil {
		return x.WasmHash
	}
	return ""
}

func (x *ContractCreatedEvent) GetCreateHostFunctionType() string {
	if x != nil {
		return x.CreateHostFunctionType
	}
	return ""
}

func (x *ContractCreatedEvent) GetConstructorInvoked() bool {
	if x != nil {
		return x.ConstructorInvoked
	}
	return false
}

func (x *ContractCreatedEvent) GetConstructorName() string {
	if x != nil {
		return x.ConstructorName
	}
	return ""
}

func (x *ContractCreatedEvent) GetConstructorArgs() []string {
	if x != nil {
		return x.ConstructorArgs
	}
	return nil
}

func (x *ContractCreatedEvent) GetContractInstanceCreated() bool {
	if x != nil {
		return x.ContractInstanceCreated
	}
	return false
}

func (x *ContractCreatedEvent) GetInitializedState() []*StateEntry {
	if x != nil {
		return x.InitializedState
	}
	return nil
}

func (x *ContractCreatedEvent) GetTtlExtendedToLedger() uint32 {
	if x != nil {
		return x.TtlExtendedToLedger
	}
	return 0
}

func (x *ContractCreatedEvent) GetClassificationHint() string {
	if x != nil {
		return x.ClassificationHint
	}
	return ""
}

func (x *ContractCreatedEvent) GetClassificationReasons() []string {
	if x != nil {
		return x.ClassificationReasons
	}
	return nil
}

func (x *ContractCreatedEvent) GetFamilyHint() string {
	if x != nil {
		return x.FamilyHint
	}
	return ""
}

func (x *ContractCreatedEvent) GetFamilyConfidence() float64 {
	if x != nil {
		return x.FamilyConfidence
	}
	return 0
}

func (x *ContractCreatedEvent) GetFamilyReasons() []string {
	if x != nil {
		return x.FamilyReasons
	}
	return nil
}

func (x *ContractCreatedEvent) GetFamilyTags() []string {
	if x != nil {
		return x.FamilyTags
	}
	return nil
}

func (x *ContractCreatedEvent) GetFamilyCandidates() []*FamilyCandidate {
	if x != nil {
		return x.FamilyCandidates
	}
	return nil
}

var File_contract_created_proto protoreflect.FileDescriptor

const file_contract_created_proto_rawDesc = "" +
	"\n" +
	"\x16contract_created.proto\x12\x10contract_created\"\xf3\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\x05R\x0eoperationIndex\x12(\n" +
	"\x10in_successful_tx\x18\x06 \x01(\bR\x0einSuccessfulTx\"r\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\tR\n" +
	"durability\"\x92\x01\n" +
	"\x0fFamilyCandidate\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x19\n" +
	"\brule_ids\x18\x05 \x03(\tR\aruleIds\"\xdc\a\n" +
	"\x14ContractCreatedEvent\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.contract_created.EventMetaR\x04meta\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12\x1a\n" +
	"\bdeployer\x18\x03 \x01(\tR\bdeployer\x12)\n" +
	"\x10preimage_address\x18\x04 \x01(\tR\x0fpreimageAddress\x12\x19\n" +
	"\bsalt_hex\x18\x05 \x01(\tR\asaltHex\x12'\n" +
	"\x0fexecutable_type\x18\x06 \x01(\tR\x0eexecutableType\x12\x1b\n" +
	"\twasm_hash\x18\a \x01(\tR\bwasmHash\x129\n" +
	"\x19create_host_function_type\x18\b \x01(\tR\x16createHostFunctionType\x12/\n" +
	"\x13constructor_invoked\x18\t \x01(\bR\x12constructorInvoked\x12)\n" +
	"\x10constructor_name\x18\n" +
	" \x01(\tR\x0fconstructorName\x12)\n" +
	"\x10constructor_args\x18\v \x03(\tR\x0fconstructorArgs\x12:\n" +
	"\x19contract_instance_created\x18\f \x01(\bR\x17contractInstanceCreated\x12I\n" +
	"\x11initialized_state\x18\r \x03(\v2\x1c.contract_created.StateEntryR\x10initializedState\x123\n" +
	"\x16ttl_extended_to_ledger\x18\x0e \x01(\rR\x13ttlExtendedToLedger\x12/\n" +
	"\x13classification_hint\x18\x0f \x01(\tR\x12classificationHint\x125\n" +
	"\x16classification_reasons\x18\x10 \x03(\tR\x15classificationReasons\x12\x1f\n" +
	"\vfamily_hint\x18\x11 \x01(\tR\n" +
	"familyHint\x12+\n" +
	"\x11family_confidence\x18\x12 \x01(\x01R\x10familyConfidence\x12%\n" +
	"\x0efamily_reasons\x18\x13 \x03(\tR\rfamilyReasons\x12\x1f\n" +
	"\vfamily_tags\x18\x14 \x03(\tR\n" +
	"familyTags\x12N\n" +
	"\x11family_candidates\x18\x15 \x03(\v2!.contract_created.FamilyCandidateR\x10familyCandidatesB\\ZZgithub.com/withObsrvr/nebu-processor-registry/processors/contract-created;contract_createdb\x06proto3"

var (
	file_contract_created_proto_rawDescOnce sync.Once
	file_contract_created_proto_rawDescData []byte
)

func file_contract_created_proto_rawDescGZIP() []byte {
	file_contract_created_proto_rawDescOnce.Do(func() {
		file_contract_created_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_created_proto_rawDesc), len(file_contract_created_proto_rawDesc)))
	})
	return file_contract_created_proto_rawDescData
}

var file_contract_created_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contract_created_proto_goTypes = []any{
	(*EventMeta)(nil),            // 0: contract_created.EventMeta
	(*StateEntry)(nil),           // 1: contract_created.StateEntry
	(*FamilyCandidate)(nil),      // 2: contract_created.FamilyCandidate
	(*ContractCreatedEvent)(nil), // 3: contract_created.ContractCreatedEvent
}
var file_contract_created_proto_depIdxs = []int32{
	0, // 0: contract_created.ContractCreatedEvent.meta:type_name -> contract_created.EventMeta
	1, // 1: contract_created.ContractCreatedEvent.initialized_state:type_name -> contract_created.StateEntry
	2, // 2: contract_created.ContractCreatedEvent.family_candidates:type_name -> contract_created.FamilyCandidate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contract_created_proto_init() }
func file_contract_created_proto_init() {
	if File_contract_created_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_created_proto_rawDesc), len(file_contract_created_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_created_proto_goTypes,
		DependencyIndexes: file_contract_created_proto_depIdxs,
		MessageInfos:      file_contract_created_proto_msgTypes,
	}.Build()
	File_contract_created_proto = out.File
	file_contract_created_proto_goTypes = nil
	file_contract_created_proto_depIdxs = nil
}
