// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ledger_change_stats.proto

package ledger_change_stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LedgerChangeStats counts every ledger entry change in one ledger, split by
// change type, by the reason the change occurred, and by the type of entry
// that changed. It also reports the entries evicted from the ledger at close.
//
// Unlike contract-state, which sees contract data only, this walks the full
// change stream: accounts, trustlines, offers, claimable balances, liquidity
// pools, contract data and code, config settings, and TTL entries — and
// includes fee, refund, and protocol-upgrade changes alongside operation ones.
type LedgerChangeStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence       uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix         int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	LedgerEntriesCreated uint32                 `protobuf:"varint,3,opt,name=ledger_entries_created,json=ledgerEntriesCreated,proto3" json:"ledger_entries_created,omitempty"`
	LedgerEntriesUpdated uint32                 `protobuf:"varint,4,opt,name=ledger_entries_updated,json=ledgerEntriesUpdated,proto3" json:"ledger_entries_updated,omitempty"`
	LedgerEntriesDeleted uint32                 `protobuf:"varint,5,opt,name=ledger_entries_deleted,json=ledgerEntriesDeleted,proto3" json:"ledger_entries_deleted,omitempty"`
	// Entries brought back from the archive by paying to restore them.
	//
	// This is read from LedgerEntryChangeType directly. Deriving the change type
	// from whether Pre/Post are nil — as the original nebu example did — cannot
	// distinguish a restore from a create, so restorations were previously
	// invisible.
	LedgerEntriesRestored uint32 `protobuf:"varint,6,opt,name=ledger_entries_restored,json=ledgerEntriesRestored,proto3" json:"ledger_entries_restored,omitempty"`
	// State snapshots. These are not mutations; they record an entry's value
	// before a transaction observed it.
	//
	// IN PRACTICE THIS IS ALWAYS ZERO. The ingest change reader elides state
	// entries (`case LedgerEntryChangeTypeLedgerEntryState: continue` in
	// GetChangesFromLedgerEntryChanges), so none ever reach this processor. Do
	// not build on this field.
	//
	// The counter is kept so that every change type lands in exactly one bucket
	// and the five sum to total_changes. Dropping it would leave a silent hole if
	// a future reader starts emitting state entries.
	LedgerEntriesState uint32 `protobuf:"varint,7,opt,name=ledger_entries_state,json=ledgerEntriesState,proto3" json:"ledger_entries_state,omitempty"`
	// Sum of every change seen, state entries included.
	TotalChanges            uint32 `protobuf:"varint,8,opt,name=total_changes,json=totalChanges,proto3" json:"total_changes,omitempty"`
	FeeRelatedChanges       uint32 `protobuf:"varint,10,opt,name=fee_related_changes,json=feeRelatedChanges,proto3" json:"fee_related_changes,omitempty"`
	TxRelatedChanges        uint32 `protobuf:"varint,11,opt,name=tx_related_changes,json=txRelatedChanges,proto3" json:"tx_related_changes,omitempty"`
	OperationRelatedChanges uint32 `protobuf:"varint,12,opt,name=operation_related_changes,json=operationRelatedChanges,proto3" json:"operation_related_changes,omitempty"`
	// Refund of the unspent Soroban resource fee after execution.
	FeeRefundRelatedChanges uint32 `protobuf:"varint,13,opt,name=fee_refund_related_changes,json=feeRefundRelatedChanges,proto3" json:"fee_refund_related_changes,omitempty"`
	// Changes applied by a protocol upgrade rather than by any transaction.
	UpgradeRelatedChanges uint32 `protobuf:"varint,14,opt,name=upgrade_related_changes,json=upgradeRelatedChanges,proto3" json:"upgrade_related_changes,omitempty"`
	// Changes whose reason the SDK could not classify. Non-zero here means the
	// classifier is behind the protocol; it is surfaced rather than folded into
	// another bucket.
	UnknownReasonChanges uint32 `protobuf:"varint,15,opt,name=unknown_reason_changes,json=unknownReasonChanges,proto3" json:"unknown_reason_changes,omitempty"`
	// One entry per LedgerEntryType that saw at least one change, ordered by the
	// XDR enum so output is deterministic across runs.
	EntryTypes []*EntryTypeChangeCounts `protobuf:"bytes,20,rep,name=entry_types,json=entryTypes,proto3" json:"entry_types,omitempty"`
	// Entries evicted at ledger close because their lifetime ran out. Eviction
	// is a ledger-level event carried on LedgerCloseMeta, not a transaction
	// change, so it appears nowhere in the change stream above.
	EvictedKeys uint32 `protobuf:"varint,30,opt,name=evicted_keys,json=evictedKeys,proto3" json:"evicted_keys,omitempty"`
	// Evicted key counts by entry type, same ordering rule as entry_types.
	EvictedByType []*EntryTypeCount `protobuf:"bytes,31,rep,name=evicted_by_type,json=evictedByType,proto3" json:"evicted_by_type,omitempty"`
	// False when this ledger's meta version predates eviction reporting. Callers
	// must not read evicted_keys == 0 as "nothing was evicted" without checking
	// this first.
	EvictionAvailable bool `protobuf:"varint,32,opt,name=eviction_available,json=evictionAvailable,proto3" json:"eviction_available,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedgerChangeStats) Reset() {
	*x = LedgerChangeStats{}
	mi := &file_ledger_change_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerChangeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerChangeStats) ProtoMessage() {}

func (x *LedgerChangeStats) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_change_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerChangeStats.ProtoReflect.Descriptor instead.
func (*LedgerChangeStats) Descriptor() ([]byte, []int) {
	return file_ledger_change_stats_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerChangeStats) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *LedgerChangeStats) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesCreated() uint32 {
	if x != nil {
		return x.LedgerEntriesCreated
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesUpdated() uint32 {
	if x != nil {
		return x.LedgerEntriesUpdated
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesDeleted() uint32 {
	if x != nil {
		return x.LedgerEntriesDeleted
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesRestored() uint32 {
	if x != nil {
		return x.LedgerEntriesRestored
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesState() uint32 {
	if x != nil {
		return x.LedgerEntriesState
	}
	return 0
}

func (x *LedgerChangeStats) GetTotalChanges() uint32 {
	if x != nil {
		return x.TotalChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetFeeRelatedChanges() uint32 {
	if x != nil {
		return x.FeeRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetTxRelatedChanges() uint32 {
	if x != nil {
		return x.TxRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetOperationRelatedChanges() uint32 {
	if x != nil {
		return x.OperationRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetFeeRefundRelatedChanges() uint32 {
	if x != nil {
		return x.FeeRefundRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetUpgradeRelatedChanges() uint32 {
	if x != nil {
		return x.UpgradeRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetUnknownReasonChanges() uint32 {
	if x != nil {
		return x.UnknownReasonChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetEntryTypes() []*EntryTypeChangeCounts {
	if x != nil {
		return x.EntryTypes
	}
	return nil
}

func (x *LedgerChangeStats) GetEvictedKeys() uint32 {
	if x != nil {
		return x.EvictedKeys
	}
	return 0
}

func (x *LedgerChangeStats) GetEvictedByType() []*EntryTypeCount {
	if x != nil {
		return x.EvictedByType
	}
	return nil
}

func (x *LedgerChangeStats) GetEvictionAvailable() bool {
	if x != nil {
		return x.EvictionAvailable
	}
	return false
}

// EntryTypeChangeCounts is one ledger entry type's change profile.
type EntryTypeChangeCounts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lowercase snake_case name: "account", "trustline", "offer", "data",
	// "claimable_balance", "liquidity_pool", "contract_data", "contract_code",
	// "config_setting", "ttl".
	EntryType     string `protobuf:"bytes,1,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Created       uint32 `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated       uint32 `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted       uint32 `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Restored      uint32 `protobuf:"varint,5,opt,name=restored,proto3" json:"restored,omitempty"`
	State         uint32 `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Total         uint32 `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryTypeChangeCounts) Reset() {
	*x = EntryTypeChangeCounts{}
	mi := &file_ledger_change_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryTypeChangeCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryTypeChangeCounts) ProtoMessage() {}

func (x *EntryTypeChangeCounts) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_change_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryTypeChangeCounts.ProtoReflect.Descriptor instead.
func (*EntryTypeChangeCounts) Descriptor() ([]byte, []int) {
	return file_ledger_change_stats_proto_rawDescGZIP(), []int{1}
}

func (x *EntryTypeChangeCounts) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *EntryTypeChangeCounts) GetCreated() uint32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *EntryTypeChangeCounts) GetUpdated() uint32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *EntryTypeChangeCounts) GetDeleted() uint32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *EntryTypeChangeCounts) GetRestored() uint32 {
	if x != nil {
		return x.Restored
	}
	return 0
}

func (x *EntryTypeChangeCounts) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *EntryTypeChangeCounts) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// EntryTypeCount is a plain count keyed by entry type.
type EntryTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryType     string                 `protobuf:"bytes,1,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryTypeCount) Reset() {
	*x = EntryTypeCount{}
	mi := &file_ledger_change_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryTypeCount) ProtoMessage() {}

func (x *EntryTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_change_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryTypeCount.ProtoReflect.Descriptor instead.
func (*EntryTypeCount) Descriptor() ([]byte, []int) {
	return file_ledger_change_stats_proto_rawDescGZIP(), []int{2}
}

func (x *EntryTypeCount) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *EntryTypeCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_ledger_change_stats_proto protoreflect.FileDescriptor

const file_ledger_change_stats_proto_rawDesc = "" +
	"\n" +
	"\x19ledger_change_stats.proto\x12\x13ledger_change_stats\"\xc4\a\n" +
	"\x11LedgerChangeStats\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x124\n" +
	"\x16ledger_entries_created\x18\x03 \x01(\rR\x14ledgerEntriesCreated\x124\n" +
	"\x16ledger_entries_updated\x18\x04 \x01(\rR\x14ledgerEntriesUpdated\x124\n" +
	"\x16ledger_entries_deleted\x18\x05 \x01(\rR\x14ledgerEntriesDeleted\x126\n" +
	"\x17ledger_entries_restored\x18\x06 \x01(\rR\x15ledgerEntriesRestored\x120\n" +
	"\x14ledger_entries_state\x18\a \x01(\rR\x12ledgerEntriesState\x12#\n" +
	"\rtotal_changes\x18\b \x01(\rR\ftotalChanges\x12.\n" +
	"\x13fee_related_changes\x18\n" +
	" \x01(\rR\x11feeRelatedChanges\x12,\n" +
	"\x12tx_related_changes\x18\v \x01(\rR\x10txRelatedChanges\x12:\n" +
	"\x19operation_related_changes\x18\f \x01(\rR\x17operationRelatedChanges\x12;\n" +
	"\x1afee_refund_related_changes\x18\r \x01(\rR\x17feeRefundRelatedChanges\x126\n" +
	"\x17upgrade_related_changes\x18\x0e \x01(\rR\x15upgradeRelatedChanges\x124\n" +
	"\x16unknown_reason_changes\x18\x0f \x01(\rR\x14unknownReasonChanges\x12K\n" +
	"\ventry_types\x18\x14 \x03(\v2*.ledger_change_stats.EntryTypeChangeCountsR\n" +
	"entryTypes\x12!\n" +
	"\fevicted_keys\x18\x1e \x01(\rR\vevictedKeys\x12K\n" +
	"\x0fevicted_by_type\x18\x1f \x03(\v2#.ledger_change_stats.EntryTypeCountR\revictedByType\x12-\n" +
	"\x12eviction_available\x18  \x01(\bR\x11evictionAvailable\"\xcc\x01\n" +
	"\x15EntryTypeChangeCounts\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x01 \x01(\tR\tentryType\x12\x18\n" +
	"\acreated\x18\x02 \x01(\rR\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\rR\aupdated\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\rR\adeleted\x12\x1a\n" +
	"\brestored\x18\x05 \x01(\rR\brestored\x12\x14\n" +
	"\x05state\x18\x06 \x01(\rR\x05state\x12\x14\n" +
	"\x05total\x18\a \x01(\rR\x05total\"E\n" +
	"\x0eEntryTypeCount\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x01 \x01(\tR\tentryType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05countBNZLgithub.com/withObsrvr/nebu-processor-registry/processors/ledger-change-statsb\x06proto3"

var (
	file_ledger_change_stats_proto_rawDescOnce sync.Once
	file_ledger_change_stats_proto_rawDescData []byte
)

func file_ledger_change_stats_proto_rawDescGZIP() []byte {
	file_ledger_change_stats_proto_rawDescOnce.Do(func() {
		file_ledger_change_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_change_stats_proto_rawDesc), len(file_ledger_change_stats_proto_rawDesc)))
	})
	return file_ledger_change_stats_proto_rawDescData
}

var file_ledger_change_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ledger_change_stats_proto_goTypes = []any{
	(*LedgerChangeStats)(nil),     // 0: ledger_change_stats.LedgerChangeStats
	(*EntryTypeChangeCounts)(nil), // 1: ledger_change_stats.EntryTypeChangeCounts
	(*EntryTypeCount)(nil),        // 2: ledger_change_stats.EntryTypeCount
}
var file_ledger_change_stats_proto_depIdxs = []int32{
	1, // 0: ledger_change_stats.LedgerChangeStats.entry_types:type_name -> ledger_change_stats.EntryTypeChangeCounts
	2, // 1: ledger_change_stats.LedgerChangeStats.evicted_by_type:type_name -> ledger_change_stats.EntryTypeCount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ledger_change_stats_proto_init() }
func file_ledger_change_stats_proto_init() {
	if File_ledger_change_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_change_stats_proto_rawDesc), len(file_ledger_change_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_change_stats_proto_goTypes,
		DependencyIndexes: file_ledger_change_stats_proto_depIdxs,
		MessageInfos:      file_ledger_change_stats_proto_msgTypes,
	}.Build()
	File_ledger_change_stats_proto = out.File
	file_ledger_change_stats_proto_goTypes = nil
	file_ledger_change_stats_proto_depIdxs = nil
}
