// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: examples/processors/contract-invocation/proto/contract_invocation.proto

package cipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractInvocation represents a contract invocation event
type ContractInvocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event metadata (ledger, tx, operation info)
	Meta *EventMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Contract being invoked
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Account that initiated the invocation
	InvokingAccount string `protobuf:"bytes,3,opt,name=invoking_account,json=invokingAccount,proto3" json:"invoking_account,omitempty"`
	// Function being called
	FunctionName string `protobuf:"bytes,4,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// Function arguments (decoded JSON strings)
	Arguments []string `protobuf:"bytes,5,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// Whether the invocation was successful
	Successful bool `protobuf:"varint,6,opt,name=successful,proto3" json:"successful,omitempty"`
	// Diagnostic events emitted during execution
	DiagnosticEvents []*DiagnosticEvent `protobuf:"bytes,7,rep,name=diagnostic_events,json=diagnosticEvents,proto3" json:"diagnostic_events,omitempty"`
	// Cross-contract calls made during execution
	ContractCalls []*ContractCall `protobuf:"bytes,8,rep,name=contract_calls,json=contractCalls,proto3" json:"contract_calls,omitempty"`
	// State changes made during execution
	StateChanges []*StateChange `protobuf:"bytes,9,rep,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	// TTL extensions made during execution
	TtlExtensions []*TtlExtension `protobuf:"bytes,10,rep,name=ttl_extensions,json=ttlExtensions,proto3" json:"ttl_extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractInvocation) Reset() {
	*x = ContractInvocation{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractInvocation) ProtoMessage() {}

func (x *ContractInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractInvocation.ProtoReflect.Descriptor instead.
func (*ContractInvocation) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *ContractInvocation) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ContractInvocation) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractInvocation) GetInvokingAccount() string {
	if x != nil {
		return x.InvokingAccount
	}
	return ""
}

func (x *ContractInvocation) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ContractInvocation) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ContractInvocation) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ContractInvocation) GetDiagnosticEvents() []*DiagnosticEvent {
	if x != nil {
		return x.DiagnosticEvents
	}
	return nil
}

func (x *ContractInvocation) GetContractCalls() []*ContractCall {
	if x != nil {
		return x.ContractCalls
	}
	return nil
}

func (x *ContractInvocation) GetStateChanges() []*StateChange {
	if x != nil {
		return x.StateChanges
	}
	return nil
}

func (x *ContractInvocation) GetTtlExtensions() []*TtlExtension {
	if x != nil {
		return x.TtlExtensions
	}
	return nil
}

// EventMeta contains metadata about the invocation
type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   uint32                 `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,6,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

// DiagnosticEvent represents a diagnostic event emitted during contract execution
type DiagnosticEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract that emitted the event
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Event topics (decoded as JSON strings)
	Topics []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// Event data (decoded as JSON string)
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Whether event was in successful contract call
	InSuccessfulCall bool `protobuf:"varint,4,opt,name=in_successful_call,json=inSuccessfulCall,proto3" json:"in_successful_call,omitempty"`
	// Event type (0=system, 1=contract, 2=diagnostic)
	EventType     uint32 `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiagnosticEvent) Reset() {
	*x = DiagnosticEvent{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticEvent) ProtoMessage() {}

func (x *DiagnosticEvent) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticEvent.ProtoReflect.Descriptor instead.
func (*DiagnosticEvent) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *DiagnosticEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *DiagnosticEvent) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *DiagnosticEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *DiagnosticEvent) GetInSuccessfulCall() bool {
	if x != nil {
		return x.InSuccessfulCall
	}
	return false
}

func (x *DiagnosticEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

// ContractCall represents a contract-to-contract call
type ContractCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source contract making the call
	FromContract string `protobuf:"bytes,1,opt,name=from_contract,json=fromContract,proto3" json:"from_contract,omitempty"`
	// Target contract being called
	ToContract string `protobuf:"bytes,2,opt,name=to_contract,json=toContract,proto3" json:"to_contract,omitempty"`
	// Function being called
	Function string `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	// Function arguments (decoded as JSON strings)
	Arguments []string `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// Call depth in the execution tree
	CallDepth uint32 `protobuf:"varint,5,opt,name=call_depth,json=callDepth,proto3" json:"call_depth,omitempty"`
	// Authorization type: "source_account", "contract", or "inferred"
	AuthType string `protobuf:"bytes,6,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	// Whether the call was successful
	Successful bool `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	// Execution order within the transaction
	ExecutionOrder uint32 `protobuf:"varint,8,opt,name=execution_order,json=executionOrder,proto3" json:"execution_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractCall) Reset() {
	*x = ContractCall{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCall) ProtoMessage() {}

func (x *ContractCall) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCall.ProtoReflect.Descriptor instead.
func (*ContractCall) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{3}
}

func (x *ContractCall) GetFromContract() string {
	if x != nil {
		return x.FromContract
	}
	return ""
}

func (x *ContractCall) GetToContract() string {
	if x != nil {
		return x.ToContract
	}
	return ""
}

func (x *ContractCall) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ContractCall) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ContractCall) GetCallDepth() uint32 {
	if x != nil {
		return x.CallDepth
	}
	return 0
}

func (x *ContractCall) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *ContractCall) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ContractCall) GetExecutionOrder() uint32 {
	if x != nil {
		return x.ExecutionOrder
	}
	return 0
}

// StateChange represents a contract state change
type StateChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract whose state changed
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// State key (decoded as JSON string)
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Old value (decoded as JSON string, empty for creates)
	OldValue string `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	// New value (decoded as JSON string, empty for deletes)
	NewValue string `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	// Operation type: "create", "update", "delete"
	Operation     string `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{4}
}

func (x *StateChange) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *StateChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateChange) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *StateChange) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *StateChange) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// TtlExtension represents a TTL extension for contract data
type TtlExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract whose TTL was extended
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Old TTL value
	OldTtl uint32 `protobuf:"varint,2,opt,name=old_ttl,json=oldTtl,proto3" json:"old_ttl,omitempty"`
	// New TTL value
	NewTtl        uint32 `protobuf:"varint,3,opt,name=new_ttl,json=newTtl,proto3" json:"new_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtlExtension) Reset() {
	*x = TtlExtension{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtlExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtlExtension) ProtoMessage() {}

func (x *TtlExtension) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtlExtension.ProtoReflect.Descriptor instead.
func (*TtlExtension) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{5}
}

func (x *TtlExtension) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *TtlExtension) GetOldTtl() uint32 {
	if x != nil {
		return x.OldTtl
	}
	return 0
}

func (x *TtlExtension) GetNewTtl() uint32 {
	if x != nil {
		return x.NewTtl
	}
	return 0
}

// GetInvocationsRequest specifies a bounded range of ledgers to process
type GetInvocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start ledger sequence (inclusive)
	StartLedger uint32 `protobuf:"varint,1,opt,name=start_ledger,json=startLedger,proto3" json:"start_ledger,omitempty"`
	// End ledger sequence (inclusive)
	EndLedger     uint32 `protobuf:"varint,2,opt,name=end_ledger,json=endLedger,proto3" json:"end_ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvocationsRequest) Reset() {
	*x = GetInvocationsRequest{}
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvocationsRequest) ProtoMessage() {}

func (x *GetInvocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvocationsRequest.ProtoReflect.Descriptor instead.
func (*GetInvocationsRequest) Descriptor() ([]byte, []int) {
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvocationsRequest) GetStartLedger() uint32 {
	if x != nil {
		return x.StartLedger
	}
	return 0
}

func (x *GetInvocationsRequest) GetEndLedger() uint32 {
	if x != nil {
		return x.EndLedger
	}
	return 0
}

var File_examples_processors_contract_invocation_proto_contract_invocation_proto protoreflect.FileDescriptor

const file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDesc = "" +
	"\n" +
	"Gexamples/processors/contract-invocation/proto/contract_invocation.proto\x12\x18nebu.contract_invocation\"\xbe\x04\n" +
	"\x12ContractInvocation\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.nebu.contract_invocation.EventMetaR\x04meta\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12)\n" +
	"\x10invoking_account\x18\x03 \x01(\tR\x0finvokingAccount\x12#\n" +
	"\rfunction_name\x18\x04 \x01(\tR\ffunctionName\x12\x1c\n" +
	"\targuments\x18\x05 \x03(\tR\targuments\x12\x1e\n" +
	"\n" +
	"successful\x18\x06 \x01(\bR\n" +
	"successful\x12V\n" +
	"\x11diagnostic_events\x18\a \x03(\v2).nebu.contract_invocation.DiagnosticEventR\x10diagnosticEvents\x12M\n" +
	"\x0econtract_calls\x18\b \x03(\v2&.nebu.contract_invocation.ContractCallR\rcontractCalls\x12J\n" +
	"\rstate_changes\x18\t \x03(\v2%.nebu.contract_invocation.StateChangeR\fstateChanges\x12M\n" +
	"\x0ettl_extensions\x18\n" +
	" \x03(\v2&.nebu.contract_invocation.TtlExtensionR\rttlExtensions\"\xf3\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\rR\x0eoperationIndex\x12(\n" +
	"\x10in_successful_tx\x18\x06 \x01(\bR\x0einSuccessfulTx\"\xab\x01\n" +
	"\x0fDiagnosticEvent\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12,\n" +
	"\x12in_successful_call\x18\x04 \x01(\bR\x10inSuccessfulCall\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\rR\teventType\"\x93\x02\n" +
	"\fContractCall\x12#\n" +
	"\rfrom_contract\x18\x01 \x01(\tR\ffromContract\x12\x1f\n" +
	"\vto_contract\x18\x02 \x01(\tR\n" +
	"toContract\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\x12\x1c\n" +
	"\targuments\x18\x04 \x03(\tR\targuments\x12\x1d\n" +
	"\n" +
	"call_depth\x18\x05 \x01(\rR\tcallDepth\x12\x1b\n" +
	"\tauth_type\x18\x06 \x01(\tR\bauthType\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\x12'\n" +
	"\x0fexecution_order\x18\b \x01(\rR\x0eexecutionOrder\"\x98\x01\n" +
	"\vStateChange\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x04 \x01(\tR\bnewValue\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\"a\n" +
	"\fTtlExtension\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x17\n" +
	"\aold_ttl\x18\x02 \x01(\rR\x06oldTtl\x12\x17\n" +
	"\anew_ttl\x18\x03 \x01(\rR\x06newTtl\"Y\n" +
	"\x15GetInvocationsRequest\x12!\n" +
	"\fstart_ledger\x18\x01 \x01(\rR\vstartLedger\x12\x1d\n" +
	"\n" +
	"end_ledger\x18\x02 \x01(\rR\tendLedger2\x8e\x01\n" +
	"\x19ContractInvocationService\x12q\n" +
	"\x0eGetInvocations\x12/.nebu.contract_invocation.GetInvocationsRequest\x1a,.nebu.contract_invocation.ContractInvocation0\x01BOZMgithub.com/withObsrvr/nebu-processor-registry/processors/contract-invocation/proto;cipbb\x06proto3"

var (
	file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescOnce sync.Once
	file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescData []byte
)

func file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescGZIP() []byte {
	file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescOnce.Do(func() {
		file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDesc), len(file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDesc)))
	})
	return file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDescData
}

var file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_examples_processors_contract_invocation_proto_contract_invocation_proto_goTypes = []any{
	(*ContractInvocation)(nil),    // 0: nebu.contract_invocation.ContractInvocation
	(*EventMeta)(nil),             // 1: nebu.contract_invocation.EventMeta
	(*DiagnosticEvent)(nil),       // 2: nebu.contract_invocation.DiagnosticEvent
	(*ContractCall)(nil),          // 3: nebu.contract_invocation.ContractCall
	(*StateChange)(nil),           // 4: nebu.contract_invocation.StateChange
	(*TtlExtension)(nil),          // 5: nebu.contract_invocation.TtlExtension
	(*GetInvocationsRequest)(nil), // 6: nebu.contract_invocation.GetInvocationsRequest
}
var file_examples_processors_contract_invocation_proto_contract_invocation_proto_depIdxs = []int32{
	1, // 0: nebu.contract_invocation.ContractInvocation.meta:type_name -> nebu.contract_invocation.EventMeta
	2, // 1: nebu.contract_invocation.ContractInvocation.diagnostic_events:type_name -> nebu.contract_invocation.DiagnosticEvent
	3, // 2: nebu.contract_invocation.ContractInvocation.contract_calls:type_name -> nebu.contract_invocation.ContractCall
	4, // 3: nebu.contract_invocation.ContractInvocation.state_changes:type_name -> nebu.contract_invocation.StateChange
	5, // 4: nebu.contract_invocation.ContractInvocation.ttl_extensions:type_name -> nebu.contract_invocation.TtlExtension
	6, // 5: nebu.contract_invocation.ContractInvocationService.GetInvocations:input_type -> nebu.contract_invocation.GetInvocationsRequest
	0, // 6: nebu.contract_invocation.ContractInvocationService.GetInvocations:output_type -> nebu.contract_invocation.ContractInvocation
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_examples_processors_contract_invocation_proto_contract_invocation_proto_init() }
func file_examples_processors_contract_invocation_proto_contract_invocation_proto_init() {
	if File_examples_processors_contract_invocation_proto_contract_invocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDesc), len(file_examples_processors_contract_invocation_proto_contract_invocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_processors_contract_invocation_proto_contract_invocation_proto_goTypes,
		DependencyIndexes: file_examples_processors_contract_invocation_proto_contract_invocation_proto_depIdxs,
		MessageInfos:      file_examples_processors_contract_invocation_proto_contract_invocation_proto_msgTypes,
	}.Build()
	File_examples_processors_contract_invocation_proto_contract_invocation_proto = out.File
	file_examples_processors_contract_invocation_proto_contract_invocation_proto_goTypes = nil
	file_examples_processors_contract_invocation_proto_contract_invocation_proto_depIdxs = nil
}
