// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: examples/processors/contract-invocation/proto/contract_invocation.proto

package cipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractInvocationService_GetInvocations_FullMethodName = "/nebu.contract_invocation.ContractInvocationService/GetInvocations"
)

// ContractInvocationServiceClient is the client API for ContractInvocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContractInvocationService streams contract invocation events from Stellar ledgers
type ContractInvocationServiceClient interface {
	// GetInvocations streams contract invocation events from a bounded ledger range
	GetInvocations(ctx context.Context, in *GetInvocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContractInvocation], error)
}

type contractInvocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractInvocationServiceClient(cc grpc.ClientConnInterface) ContractInvocationServiceClient {
	return &contractInvocationServiceClient{cc}
}

func (c *contractInvocationServiceClient) GetInvocations(ctx context.Context, in *GetInvocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContractInvocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContractInvocationService_ServiceDesc.Streams[0], ContractInvocationService_GetInvocations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetInvocationsRequest, ContractInvocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContractInvocationService_GetInvocationsClient = grpc.ServerStreamingClient[ContractInvocation]

// ContractInvocationServiceServer is the server API for ContractInvocationService service.
// All implementations must embed UnimplementedContractInvocationServiceServer
// for forward compatibility.
//
// ContractInvocationService streams contract invocation events from Stellar ledgers
type ContractInvocationServiceServer interface {
	// GetInvocations streams contract invocation events from a bounded ledger range
	GetInvocations(*GetInvocationsRequest, grpc.ServerStreamingServer[ContractInvocation]) error
	mustEmbedUnimplementedContractInvocationServiceServer()
}

// UnimplementedContractInvocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractInvocationServiceServer struct{}

func (UnimplementedContractInvocationServiceServer) GetInvocations(*GetInvocationsRequest, grpc.ServerStreamingServer[ContractInvocation]) error {
	return status.Error(codes.Unimplemented, "method GetInvocations not implemented")
}
func (UnimplementedContractInvocationServiceServer) mustEmbedUnimplementedContractInvocationServiceServer() {
}
func (UnimplementedContractInvocationServiceServer) testEmbeddedByValue() {}

// UnsafeContractInvocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractInvocationServiceServer will
// result in compilation errors.
type UnsafeContractInvocationServiceServer interface {
	mustEmbedUnimplementedContractInvocationServiceServer()
}

func RegisterContractInvocationServiceServer(s grpc.ServiceRegistrar, srv ContractInvocationServiceServer) {
	// If the following call panics, it indicates UnimplementedContractInvocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractInvocationService_ServiceDesc, srv)
}

func _ContractInvocationService_GetInvocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetInvocationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractInvocationServiceServer).GetInvocations(m, &grpc.GenericServerStream[GetInvocationsRequest, ContractInvocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContractInvocationService_GetInvocationsServer = grpc.ServerStreamingServer[ContractInvocation]

// ContractInvocationService_ServiceDesc is the grpc.ServiceDesc for ContractInvocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractInvocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebu.contract_invocation.ContractInvocationService",
	HandlerType: (*ContractInvocationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInvocations",
			Handler:       _ContractInvocationService_GetInvocations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "examples/processors/contract-invocation/proto/contract_invocation.proto",
}
