// Protocol buffer definition for contract state processor.
//
// This schema defines the output format for contract data state changes
// extracted from Stellar ledgers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: contract_state.proto

package contract_state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Durability of contract data entries
type Durability int32

const (
	// Persistent data (survives across ledger boundaries until TTL expires)
	Durability_PERSISTENT Durability = 0
	// Temporary data (cheaper, shorter TTL)
	Durability_TEMPORARY Durability = 1
)

// Enum value maps for Durability.
var (
	Durability_name = map[int32]string{
		0: "PERSISTENT",
		1: "TEMPORARY",
	}
	Durability_value = map[string]int32{
		"PERSISTENT": 0,
		"TEMPORARY":  1,
	}
)

func (x Durability) Enum() *Durability {
	p := new(Durability)
	*p = x
	return p
}

func (x Durability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Durability) Descriptor() protoreflect.EnumDescriptor {
	return file_contract_state_proto_enumTypes[0].Descriptor()
}

func (Durability) Type() protoreflect.EnumType {
	return &file_contract_state_proto_enumTypes[0]
}

func (x Durability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Durability.Descriptor instead.
func (Durability) EnumDescriptor() ([]byte, []int) {
	return file_contract_state_proto_rawDescGZIP(), []int{0}
}

// ContractStateEvent represents a contract data state change in a ledger.
type ContractStateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract ID (strkey-encoded, C... address)
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Hash of the ledger key
	LedgerKeyHash string `protobuf:"bytes,2,opt,name=ledger_key_hash,json=ledgerKeyHash,proto3" json:"ledger_key_hash,omitempty"`
	// Durability of the contract data entry
	Durability Durability `protobuf:"varint,3,opt,name=durability,proto3,enum=contract_state.Durability" json:"durability,omitempty"`
	// Operation type: "create", "update", or "delete"
	Operation string `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	// Key (base64-encoded XDR)
	KeyXdr string `protobuf:"bytes,5,opt,name=key_xdr,json=keyXdr,proto3" json:"key_xdr,omitempty"`
	// Value (base64-encoded XDR, empty for deletes)
	ValXdr string `protobuf:"bytes,6,opt,name=val_xdr,json=valXdr,proto3" json:"val_xdr,omitempty"`
	// Key symbol (if the key is a simple symbol, extracted for convenience)
	KeySymbol string `protobuf:"bytes,7,opt,name=key_symbol,json=keySymbol,proto3" json:"key_symbol,omitempty"`
	// Event metadata
	Meta          *EventMeta `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractStateEvent) Reset() {
	*x = ContractStateEvent{}
	mi := &file_contract_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractStateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractStateEvent) ProtoMessage() {}

func (x *ContractStateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_contract_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractStateEvent.ProtoReflect.Descriptor instead.
func (*ContractStateEvent) Descriptor() ([]byte, []int) {
	return file_contract_state_proto_rawDescGZIP(), []int{0}
}

func (x *ContractStateEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractStateEvent) GetLedgerKeyHash() string {
	if x != nil {
		return x.LedgerKeyHash
	}
	return ""
}

func (x *ContractStateEvent) GetDurability() Durability {
	if x != nil {
		return x.Durability
	}
	return Durability_PERSISTENT
}

func (x *ContractStateEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ContractStateEvent) GetKeyXdr() string {
	if x != nil {
		return x.KeyXdr
	}
	return ""
}

func (x *ContractStateEvent) GetValXdr() string {
	if x != nil {
		return x.ValXdr
	}
	return ""
}

func (x *ContractStateEvent) GetKeySymbol() string {
	if x != nil {
		return x.KeySymbol
	}
	return ""
}

func (x *ContractStateEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EventMeta contains chronological context for the event
type EventMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger sequence number
	LedgerSequence uint32 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Ledger close timestamp (Unix seconds)
	ClosedAtUnix int64 `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	// Transaction hash (hex-encoded)
	TxHash string `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Transaction index within the ledger
	TransactionIndex uint32 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_contract_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_contract_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_contract_state_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

var File_contract_state_proto protoreflect.FileDescriptor

const file_contract_state_proto_rawDesc = "" +
	"\n" +
	"\x14contract_state.proto\x12\x0econtract_state\"\xb7\x02\n" +
	"\x12ContractStateEvent\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12&\n" +
	"\x0fledger_key_hash\x18\x02 \x01(\tR\rledgerKeyHash\x12:\n" +
	"\n" +
	"durability\x18\x03 \x01(\x0e2\x1a.contract_state.DurabilityR\n" +
	"durability\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x17\n" +
	"\akey_xdr\x18\x05 \x01(\tR\x06keyXdr\x12\x17\n" +
	"\aval_xdr\x18\x06 \x01(\tR\x06valXdr\x12\x1d\n" +
	"\n" +
	"key_symbol\x18\a \x01(\tR\tkeySymbol\x12-\n" +
	"\x04meta\x18\n" +
	" \x01(\v2\x19.contract_state.EventMetaR\x04meta\"\xa0\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex*+\n" +
	"\n" +
	"Durability\x12\x0e\n" +
	"\n" +
	"PERSISTENT\x10\x00\x12\r\n" +
	"\tTEMPORARY\x10\x01BIZGgithub.com/withObsrvr/nebu-processor-registry/processors/contract-stateb\x06proto3"

var (
	file_contract_state_proto_rawDescOnce sync.Once
	file_contract_state_proto_rawDescData []byte
)

func file_contract_state_proto_rawDescGZIP() []byte {
	file_contract_state_proto_rawDescOnce.Do(func() {
		file_contract_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_state_proto_rawDesc), len(file_contract_state_proto_rawDesc)))
	})
	return file_contract_state_proto_rawDescData
}

var file_contract_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contract_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_state_proto_goTypes = []any{
	(Durability)(0),            // 0: contract_state.Durability
	(*ContractStateEvent)(nil), // 1: contract_state.ContractStateEvent
	(*EventMeta)(nil),          // 2: contract_state.EventMeta
}
var file_contract_state_proto_depIdxs = []int32{
	0, // 0: contract_state.ContractStateEvent.durability:type_name -> contract_state.Durability
	2, // 1: contract_state.ContractStateEvent.meta:type_name -> contract_state.EventMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contract_state_proto_init() }
func file_contract_state_proto_init() {
	if File_contract_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_state_proto_rawDesc), len(file_contract_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_state_proto_goTypes,
		DependencyIndexes: file_contract_state_proto_depIdxs,
		EnumInfos:         file_contract_state_proto_enumTypes,
		MessageInfos:      file_contract_state_proto_msgTypes,
	}.Build()
	File_contract_state_proto = out.File
	file_contract_state_proto_goTypes = nil
	file_contract_state_proto_depIdxs = nil
}
