// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: examples/processors/token-transfer/proto/token_transfer_service.proto

package ttpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenTransferService_GetEvents_FullMethodName = "/nebu.ttp.TokenTransferService/GetEvents"
)

// TokenTransferServiceClient is the client API for TokenTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenTransferService streams token transfer events from Stellar ledgers.
type TokenTransferServiceClient interface {
	// GetEvents streams token transfer events from a bounded ledger range.
	// Events are emitted in ledger sequence order.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenTransferEvent], error)
}

type tokenTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenTransferServiceClient(cc grpc.ClientConnInterface) TokenTransferServiceClient {
	return &tokenTransferServiceClient{cc}
}

func (c *tokenTransferServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenTransferEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TokenTransferService_ServiceDesc.Streams[0], TokenTransferService_GetEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEventsRequest, TokenTransferEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TokenTransferService_GetEventsClient = grpc.ServerStreamingClient[TokenTransferEvent]

// TokenTransferServiceServer is the server API for TokenTransferService service.
// All implementations must embed UnimplementedTokenTransferServiceServer
// for forward compatibility.
//
// TokenTransferService streams token transfer events from Stellar ledgers.
type TokenTransferServiceServer interface {
	// GetEvents streams token transfer events from a bounded ledger range.
	// Events are emitted in ledger sequence order.
	GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[TokenTransferEvent]) error
	mustEmbedUnimplementedTokenTransferServiceServer()
}

// UnimplementedTokenTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenTransferServiceServer struct{}

func (UnimplementedTokenTransferServiceServer) GetEvents(*GetEventsRequest, grpc.ServerStreamingServer[TokenTransferEvent]) error {
	return status.Error(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedTokenTransferServiceServer) mustEmbedUnimplementedTokenTransferServiceServer() {}
func (UnimplementedTokenTransferServiceServer) testEmbeddedByValue()                              {}

// UnsafeTokenTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenTransferServiceServer will
// result in compilation errors.
type UnsafeTokenTransferServiceServer interface {
	mustEmbedUnimplementedTokenTransferServiceServer()
}

func RegisterTokenTransferServiceServer(s grpc.ServiceRegistrar, srv TokenTransferServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenTransferService_ServiceDesc, srv)
}

func _TokenTransferService_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TokenTransferServiceServer).GetEvents(m, &grpc.GenericServerStream[GetEventsRequest, TokenTransferEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TokenTransferService_GetEventsServer = grpc.ServerStreamingServer[TokenTransferEvent]

// TokenTransferService_ServiceDesc is the grpc.ServiceDesc for TokenTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebu.ttp.TokenTransferService",
	HandlerType: (*TokenTransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _TokenTransferService_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "examples/processors/token-transfer/proto/token_transfer_service.proto",
}
