// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: examples/processors/token-transfer/proto/token_transfer_service.proto

package ttpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetEventsRequest specifies a bounded range of ledgers to process.
type GetEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start ledger sequence (inclusive)
	StartLedger uint32 `protobuf:"varint,1,opt,name=start_ledger,json=startLedger,proto3" json:"start_ledger,omitempty"`
	// End ledger sequence (inclusive)
	EndLedger     uint32 `protobuf:"varint,2,opt,name=end_ledger,json=endLedger,proto3" json:"end_ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetStartLedger() uint32 {
	if x != nil {
		return x.StartLedger
	}
	return 0
}

func (x *GetEventsRequest) GetEndLedger() uint32 {
	if x != nil {
		return x.EndLedger
	}
	return 0
}

// TokenTransferEvent is the core event emitted by the processor.
// We define it here to avoid external dependencies in our proto.
// This mirrors the structure from Stellar SDK's token_transfer.TokenTransferEvent
type TokenTransferEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event metadata (ledger, tx, operation info)
	Meta *EventMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Event type (one of the following)
	//
	// Types that are valid to be assigned to Event:
	//
	//	*TokenTransferEvent_Transfer
	//	*TokenTransferEvent_Mint
	//	*TokenTransferEvent_Burn
	//	*TokenTransferEvent_Clawback
	//	*TokenTransferEvent_Fee
	Event         isTokenTransferEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTransferEvent) Reset() {
	*x = TokenTransferEvent{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferEvent) ProtoMessage() {}

func (x *TokenTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferEvent.ProtoReflect.Descriptor instead.
func (*TokenTransferEvent) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{1}
}

func (x *TokenTransferEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TokenTransferEvent) GetEvent() isTokenTransferEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TokenTransferEvent) GetTransfer() *Transfer {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetMint() *Mint {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Mint); ok {
			return x.Mint
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetBurn() *Burn {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Burn); ok {
			return x.Burn
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetClawback() *Clawback {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Clawback); ok {
			return x.Clawback
		}
	}
	return nil
}

func (x *TokenTransferEvent) GetFee() *Fee {
	if x != nil {
		if x, ok := x.Event.(*TokenTransferEvent_Fee); ok {
			return x.Fee
		}
	}
	return nil
}

type isTokenTransferEvent_Event interface {
	isTokenTransferEvent_Event()
}

type TokenTransferEvent_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,2,opt,name=transfer,proto3,oneof"`
}

type TokenTransferEvent_Mint struct {
	Mint *Mint `protobuf:"bytes,3,opt,name=mint,proto3,oneof"`
}

type TokenTransferEvent_Burn struct {
	Burn *Burn `protobuf:"bytes,4,opt,name=burn,proto3,oneof"`
}

type TokenTransferEvent_Clawback struct {
	Clawback *Clawback `protobuf:"bytes,5,opt,name=clawback,proto3,oneof"`
}

type TokenTransferEvent_Fee struct {
	Fee *Fee `protobuf:"bytes,6,opt,name=fee,proto3,oneof"`
}

func (*TokenTransferEvent_Transfer) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Mint) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Burn) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Clawback) isTokenTransferEvent_Event() {}

func (*TokenTransferEvent_Fee) isTokenTransferEvent_Event() {}

type EventMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence   uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	ClosedAtUnix     int64                  `protobuf:"varint,2,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	TxHash           string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TransactionIndex uint32                 `protobuf:"varint,4,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	OperationIndex   uint32                 `protobuf:"varint,5,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	ContractAddress  string                 `protobuf:"bytes,6,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	InSuccessfulTx   bool                   `protobuf:"varint,7,opt,name=in_successful_tx,json=inSuccessfulTx,proto3" json:"in_successful_tx,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{2}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *EventMeta) GetInSuccessfulTx() bool {
	if x != nil {
		return x.InSuccessfulTx
	}
	return false
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	AssetCode     string                 `protobuf:"bytes,3,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,4,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{3}
}

func (x *Transfer) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transfer) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Transfer) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Mint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mint) Reset() {
	*x = Mint{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mint) ProtoMessage() {}

func (x *Mint) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mint.ProtoReflect.Descriptor instead.
func (*Mint) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{4}
}

func (x *Mint) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Mint) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Mint) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *Mint) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Burn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Burn) Reset() {
	*x = Burn{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Burn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Burn) ProtoMessage() {}

func (x *Burn) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Burn.ProtoReflect.Descriptor instead.
func (*Burn) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{5}
}

func (x *Burn) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Burn) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Burn) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *Burn) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Clawback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clawback) Reset() {
	*x = Clawback{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clawback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clawback) ProtoMessage() {}

func (x *Clawback) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clawback.ProtoReflect.Descriptor instead.
func (*Clawback) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{6}
}

func (x *Clawback) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Clawback) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Clawback) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *Clawback) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	AssetCode     string                 `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetIssuer   string                 `protobuf:"bytes,3,opt,name=asset_issuer,json=assetIssuer,proto3" json:"asset_issuer,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP(), []int{7}
}

func (x *Fee) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Fee) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Fee) GetAssetIssuer() string {
	if x != nil {
		return x.AssetIssuer
	}
	return ""
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_examples_processors_token_transfer_proto_token_transfer_service_proto protoreflect.FileDescriptor

const file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDesc = "" +
	"\n" +
	"Eexamples/processors/token-transfer/proto/token_transfer_service.proto\x12\bnebu.ttp\"T\n" +
	"\x10GetEventsRequest\x12!\n" +
	"\fstart_ledger\x18\x01 \x01(\rR\vstartLedger\x12\x1d\n" +
	"\n" +
	"end_ledger\x18\x02 \x01(\rR\tendLedger\"\x99\x02\n" +
	"\x12TokenTransferEvent\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.nebu.ttp.EventMetaR\x04meta\x120\n" +
	"\btransfer\x18\x02 \x01(\v2\x12.nebu.ttp.TransferH\x00R\btransfer\x12$\n" +
	"\x04mint\x18\x03 \x01(\v2\x0e.nebu.ttp.MintH\x00R\x04mint\x12$\n" +
	"\x04burn\x18\x04 \x01(\v2\x0e.nebu.ttp.BurnH\x00R\x04burn\x120\n" +
	"\bclawback\x18\x05 \x01(\v2\x12.nebu.ttp.ClawbackH\x00R\bclawback\x12!\n" +
	"\x03fee\x18\x06 \x01(\v2\r.nebu.ttp.FeeH\x00R\x03feeB\a\n" +
	"\x05event\"\x9e\x02\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12$\n" +
	"\x0eclosed_at_unix\x18\x02 \x01(\x03R\fclosedAtUnix\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12+\n" +
	"\x11transaction_index\x18\x04 \x01(\rR\x10transactionIndex\x12'\n" +
	"\x0foperation_index\x18\x05 \x01(\rR\x0eoperationIndex\x12)\n" +
	"\x10contract_address\x18\x06 \x01(\tR\x0fcontractAddress\x12(\n" +
	"\x10in_successful_tx\x18\a \x01(\bR\x0einSuccessfulTx\"\x88\x01\n" +
	"\bTransfer\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x03 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x04 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"p\n" +
	"\x04Mint\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"t\n" +
	"\x04Burn\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"x\n" +
	"\bClawback\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"s\n" +
	"\x03Fee\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1d\n" +
	"\n" +
	"asset_code\x18\x02 \x01(\tR\tassetCode\x12!\n" +
	"\fasset_issuer\x18\x03 \x01(\tR\vassetIssuer\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount2_\n" +
	"\x14TokenTransferService\x12G\n" +
	"\tGetEvents\x12\x1a.nebu.ttp.GetEventsRequest\x1a\x1c.nebu.ttp.TokenTransferEvent0\x01BFZDgithub.com/withObsrvr/nebu/processors/core/token_transfer/proto;ttpbb\x06proto3"

var (
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescOnce sync.Once
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescData []byte
)

func file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescGZIP() []byte {
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescOnce.Do(func() {
		file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDesc), len(file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDesc)))
	})
	return file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDescData
}

var file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_examples_processors_token_transfer_proto_token_transfer_service_proto_goTypes = []any{
	(*GetEventsRequest)(nil),   // 0: nebu.ttp.GetEventsRequest
	(*TokenTransferEvent)(nil), // 1: nebu.ttp.TokenTransferEvent
	(*EventMeta)(nil),          // 2: nebu.ttp.EventMeta
	(*Transfer)(nil),           // 3: nebu.ttp.Transfer
	(*Mint)(nil),               // 4: nebu.ttp.Mint
	(*Burn)(nil),               // 5: nebu.ttp.Burn
	(*Clawback)(nil),           // 6: nebu.ttp.Clawback
	(*Fee)(nil),                // 7: nebu.ttp.Fee
}
var file_examples_processors_token_transfer_proto_token_transfer_service_proto_depIdxs = []int32{
	2, // 0: nebu.ttp.TokenTransferEvent.meta:type_name -> nebu.ttp.EventMeta
	3, // 1: nebu.ttp.TokenTransferEvent.transfer:type_name -> nebu.ttp.Transfer
	4, // 2: nebu.ttp.TokenTransferEvent.mint:type_name -> nebu.ttp.Mint
	5, // 3: nebu.ttp.TokenTransferEvent.burn:type_name -> nebu.ttp.Burn
	6, // 4: nebu.ttp.TokenTransferEvent.clawback:type_name -> nebu.ttp.Clawback
	7, // 5: nebu.ttp.TokenTransferEvent.fee:type_name -> nebu.ttp.Fee
	0, // 6: nebu.ttp.TokenTransferService.GetEvents:input_type -> nebu.ttp.GetEventsRequest
	1, // 7: nebu.ttp.TokenTransferService.GetEvents:output_type -> nebu.ttp.TokenTransferEvent
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_examples_processors_token_transfer_proto_token_transfer_service_proto_init() }
func file_examples_processors_token_transfer_proto_token_transfer_service_proto_init() {
	if File_examples_processors_token_transfer_proto_token_transfer_service_proto != nil {
		return
	}
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes[1].OneofWrappers = []any{
		(*TokenTransferEvent_Transfer)(nil),
		(*TokenTransferEvent_Mint)(nil),
		(*TokenTransferEvent_Burn)(nil),
		(*TokenTransferEvent_Clawback)(nil),
		(*TokenTransferEvent_Fee)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDesc), len(file_examples_processors_token_transfer_proto_token_transfer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_processors_token_transfer_proto_token_transfer_service_proto_goTypes,
		DependencyIndexes: file_examples_processors_token_transfer_proto_token_transfer_service_proto_depIdxs,
		MessageInfos:      file_examples_processors_token_transfer_proto_token_transfer_service_proto_msgTypes,
	}.Build()
	File_examples_processors_token_transfer_proto_token_transfer_service_proto = out.File
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_goTypes = nil
	file_examples_processors_token_transfer_proto_token_transfer_service_proto_depIdxs = nil
}
